### ISSUE TITLE
11B model `missing from the checkpoint.` for fine-tuning

### ISSUE THREAD

**Issue by jinoobaek-qz** [google-research/text-to-text-transfer-transformer#106]
commands:

```
export IDENTIFIER=${IDENTIFIER:-$(date +'%Y_%m_%d_%H_%M_%s')}
export PROJECT=some_value1
export ZONE=us-central1-a
export BUCKET=gs://some_value_2
export TPU_NAME=jin-t5-tpu
export DATA_DIR="${BUCKET}/your_data_dir_${IDENTIFIER}"
export MODEL_DIR="${BUCKET}/your_model_dir_${IDENTIFIER}"


ctpu up --name=$TPU_NAME --project=$PROJECT --zone=$ZONE --tpu-size=v3-8  \
        --tpu-only   --tf-version=1.15 --noconf


t5_mesh_transformer  \
  --tpu="${TPU_NAME}" \
  --gcp_project="${PROJECT}" \
  --tpu_zone="${ZONE}" \
  --model_dir="${MODEL_DIR}" \
  --t5_tfds_data_dir="${DATA_DIR}" \
  --gin_file="dataset.gin" \
  --gin_param="utils.tpu_mesh_shape.model_parallelism = 1" \
  --gin_param="utils.tpu_mesh_shape.tpu_topology = '2x2'" \
  --gin_param="MIXTURE_NAME = 'glue_mrpc_v002'" \
  --gin_file="gs://t5-data/pretrained_models/11B/operative_config.gin"
```

Above worked with `  --gin_file="gs://t5-data/pretrained_models/small/operative_config.gin"`

Error:
```
W0225 23:06:47.097845 140561545670272 error_handling.py:135] Reraising captured error
Traceback (most recent call last):
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/bin/t5_mesh_transformer", line 8, in <module>
    sys.exit(console_entry_point())
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/t5/models/mesh_transformer_main.py", line 214, in console_entry_point
    app.run(main)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/t5/models/mesh_transformer_main.py", line 208, in main
    model_dir=FLAGS.model_dir)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/mesh_tensorflow/transformer/utils.py", line 1733, in run
    train_dataset_fn, train_steps, ensemble_inputs)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/mesh_tensorflow/transformer/utils.py", line 1120, in train_model
    estimator.train(input_fn=input_fn, max_steps=train_steps)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1195, in _train_model_default
    saving_listeners)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1490, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 584, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1014, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 725, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1207, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1212, in _create_session
    return self._sess_creator.create_session()
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 878, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 647, in create_session
    init_fn=self._scaffold.init_fn)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_core/python/training/session_manager.py", line 290, in prepare_session
    config=config)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_core/python/training/session_manager.py", line 220, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/home/jupyter/.local/share/virtualenvs/text-to-text-transfer-transformer-TT-eYXMI/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1306, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

From /job:worker/replica:0/task:0:
Key decoder/block_006/layer_000/SelfAttention/k not found in checkpoint
         [[node save/RestoreV2_1 (defined at /lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
```

**Comment by craffel** [comment]
Is there already a checkpoint or model graph in your $MODEL_DIR? If so, TF will load that graph before it loads the checkpoint and fail. You need to make sure the MODEL_DIR is clear.

Also, you won't be able to train the 11B param model on a 2x2 with MODEL_PARALLELISM=1. You need a bigger TPU slice, and some form of model parallelism, to do that.

**Comment by jinoobaek-qz** [comment]
Thanks for the feedback on model dir. That was it. Had to unset IDENTIFIER first `export IDENTIFIER=${IDENTIFIER:-$(date +'%Y_%m_%d_%H_%M_%s')}`.

I assumed so with regards to 2x2. Was validating that it would fail there, and it did with OOM. 

It seems like europe-west-4a is the only place where v3 with bigger slices are publicly available. I'll go ahead and try there, but, does tpu v2 work out of the box by chance?

**Comment by adarob** [comment]
I could be wrong, but I think I trained on a v3-8 with parallelism 8 and
batch size of 8.

**Comment by adarob** [comment]
You could start with batch size of 1 to test but you'd need parallelism of
8 at least.

**Comment by jinoobaek-qz** [comment]
Thanks. I successfully ran fine-tuning of 11B model on v3-8 with

Like you said, these were key:
```
  --gin_param="utils.tpu_mesh_shape.model_parallelism = 8" \
  --gin_param="run.batch_size = 1" \
```

Full command:
```
export IDENTIFIER=$(date +'%Y_%m_%d_%H_%M_%s')
export PROJECT=my_project
export ZONE=us-central1-a
export BUCKET=gs://jin-t5-dev
export TPU_NAME=node-1
export DATA_DIR="${BUCKET}/your_data_dir"
export MODEL_DIR="${BUCKET}/your_model_dir_${IDENTIFIER}"

t5_mesh_transformer  \
  --tpu="${TPU_NAME}" \
  --gcp_project="${PROJECT}" \
  --tpu_zone="${ZONE}" \
  --model_dir="${MODEL_DIR}" \
  --t5_tfds_data_dir="${DATA_DIR}" \
  --gin_file="dataset.gin" \
  --gin_param="utils.tpu_mesh_shape.model_parallelism = 8" \
  --gin_param="utils.tpu_mesh_shape.tpu_topology = '2x2'" \
  --gin_param="run.batch_size = 1" \
  --gin_param="MIXTURE_NAME = 'glue_mrpc_v002'" \
  --gin_file="gs://t5-data/pretrained_models/11B/operative_config.gin"
```
