### ISSUE TITLE
Breaking change for GPU usage? tpu_mesh_shape not provided in tpu_topology

### ISSUE THREAD

**Issue by marcoalban-hidalgo** [google-research/text-to-text-transfer-transformer#126]
Execution removing tpu specific flags for gpu usage is failing. Ran the following:
```
MODEL_OPERATIVE_CONFIG="./t5-data/pretrained_models/small/operative_config.gin"
TSV_FILE="./tiny.tsv"

t5_mesh_transformer \
    --model_dir="${MODEL_DIR}" \
    --t5_tfds_data_dir="${DATA_DIR}" \
    --gin_param="utils.run.mesh_shape = 'model:1,batch:1'" \
    --gin_param="utils.run.mesh_devices = ['gpu:0']" \
    --gin_param="utils.run.train_dataset_fn = @t5.models.mesh_transformer.tsv_dataset_fn" \
    --gin_param="tsv_dataset_fn.filename = '${TSV_FILE}'" \
    --gin_file="learning_rate_schedules/constant_0_001.gin" \
    --gin_param="rn.train_steps = 1000020" \
    --gin_file="${MODEL_OPERATIVE_CONFIG}"
```
Result is:
```Traceback (most recent call last):
  File "**/projects/env-ml/bin/t5_mesh_transformer", line 8, in <module>
    sys.exit(console_entry_point())
  File "**/projects/env-ml/lib/python3.6/site-packages/t5/models/mesh_transformer_main.py", line 214, in console_entry_point
    app.run(main)
  File "**/projects/env-ml/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "**/projects/env-ml/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "**/projects/env-ml/lib/python3.6/site-packages/t5/models/mesh_transformer_main.py", line 208, in main
    model_dir=FLAGS.model_dir)
  File "**/projects/env-ml/lib/python3.6/site-packages/gin/config.py", line 1018, in gin_wrapper
    new_kwargs = copy.deepcopy(new_kwargs)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "**/projects/env-ml/lib/python3.6/site-packages/gin/config.py", line 384, in __deepcopy__
    return self._scoped_configurable_fn()
  File "**/projects/env-ml/lib/python3.6/site-packages/gin/config.py", line 1048, in gin_wrapper
    raise RuntimeError(err_str)
RuntimeError: Required bindings for `tpu_mesh_shape` not provided in config: ['tpu_topology']
```

Same thing with running:
```
t5_mesh_transformer  \
  --model_dir="${MODEL_DIR}" \
  --t5_tfds_data_dir="${DATA_DIR}" \
  --gin_file="dataset.gin" \
  --gin_param="utils.run.mesh_shape = 'model:1,batch:1'" \
  --gin_param="utils.run.mesh_devices = ['gpu:0']" \
  --gin_param="MIXTURE_NAME = 'glue_mrpc_v002'" \
  --gin_file="gs://t5-data/pretrained_models/small/operative_config.gin"
```

I tried this back in Jan and it worked (had GPU memory issue as other ticket already raised). Any suggestions? I know this is new and really appreciate and value all the work that you guys have done here.

**Comment by craffel** [comment]
Hi, I think what may be happening is that the gin binding for `utils.run.mesh_shape` is getting set to `run.mesh_shape = @mesh_tensorflow.transformer.utils.tpu_mesh_shape()` via the binding in `gs://t5-data/pretrained_models/small/operative_config.gin` and for some reason the bindings to `tpu_mesh_shape` are not being set in the operative config. Is your local file `./t5-data/pretrained_models/small/operative_config.gin` modified from the original operative config in any way? You could try removing the `run.mesh_shape = @mesh_tensorflow.transformer.utils.tpu_mesh_shape()` line from your local gin config and try again. I am sort of surprised this is happening since files are supposed to be parsed first, and then custom bindings second.

**Comment by marcoalban-hidalgo** [comment]
i didn't touch the original operative config, thanks that seemed to work :) appreciate the response

**Comment by SnehinBoston** [comment]
I did try doing the above change, however I am still facing the error. Could anyone help?
