### ISSUE TITLE
NanLossDuringTrainingError when train model from scratch

### ISSUE THREAD

**Issue by orsk-moscow** [google-research/text-to-text-transfer-transformer#210]
Hi, T5 authors,

Here is my error trace:
`tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.`

What am i doing:
run code from [this README section](https://github.com/google-research/text-to-text-transfer-transformer#training) twice

1. on TPU v2-8
2. on TPU v2-512

TPU v2-8 works fine, but trains too much time (several days). 
For training on TPU v2-512 I changed only this:
`--gin_param="utils.tpu_mesh_shape.tpu_topology = '16x16'"`

But through 400 steps model fallen several times with error `tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.`

Could you clarify, how to fix it?

**Comment by orsk-moscow** [comment]
full callstack:

`W0504 13:26:39.572035 140559419672320 preempted_hook.py:91] TPUPollingThread found TPU b'most-powerfull-tpu-node' in state READY, and health HEALTHY.
ERROR:tensorflow:Model diverged with loss = NaN.
E0504 13:26:51.418789 140562679776640 basic_session_run_hooks.py:768] Model diverged with loss = NaN.
INFO:tensorflow:training_loop marked as finished
I0504 13:26:52.141377 140562679776640 error_handling.py:108] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0504 13:26:52.141616 140562679776640 error_handling.py:142] Reraising captured error
Traceback (most recent call last):
  File "/opt/conda/bin/t5_mesh_transformer", line 8, in <module>
    sys.exit(console_entry_point())
  File "/opt/conda/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 222, in console_entry_point
    app.run(main)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 216, in main
    model_dir=FLAGS.model_dir)
  File "/opt/conda/lib/python3.7/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/opt/conda/lib/python3.7/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/opt/conda/lib/python3.7/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1738, in run
    train_dataset_fn, train_steps, ensemble_inputs)
  File "/opt/conda/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1132, in train_model
    estimator.train(input_fn=input_fn, max_steps=train_steps)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 143, in raise_errors
    six.reraise(typ, value, traceback)
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 374, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1164, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1198, in _train_model_default
    saving_listeners)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1497, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 778, in run
    run_metadata=run_metadata)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1283, in run
    run_metadata=run_metadata)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1450, in run
    run_metadata=run_metadata))
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/training/basic_session_run_hooks.py", line 769, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
  In call to configurable 'run' (<function run at 0x7fd703233ef0>)`

**Comment by adarob** [comment]
@nshazeer can you take a look?

**Comment by nshazeer** [comment]
Sorry - I have no idea what is going wrong ...  I haven't worked with the external version.  Theoretically, it should be doing the same mathematical computation, assuming it is using the same batch size.  How does the batch size get set anyway? Are there more logs that I could look at?

**Comment by orsk-moscow** [comment]
https://github.com/aivscovid19/exploring_t5/blob/text_classifier_develop/train-v2-512.log 

That is my log for training on TPU v2-512

And that is my script for training:
https://github.com/aivscovid19/exploring_t5/blob/text_classifier_develop/train-v2-512.sh

What else could be useful for you?

**Comment by nshazeer** [comment]
For some reason I get a 404 when trying to open those links.

**Comment by orsk-moscow** [comment]
Repo was private, sorry. Made it public, try once more, please.
>For some reason I get a 404 when trying to open those links.

**Comment by craffel** [comment]
Can you send the exact command you used? Did you just copy/paste from the "Training" section you linked? Was your model directory empty before you started training? The links are still 404 for me.

**Comment by orsk-moscow** [comment]
> Can you send the exact command you used?

export PROJECT='ai-vs-covid19'
export ZONE='us-central1-a'
export BUCKET='gs://igor-us-central1-f'
export TPU_NAME='the-most-powerfull-tpu'
export DATA_DIR="${BUCKET}"
export MODEL_DIR="${BUCKET}/20200504_from_scratch/v2-512/4/"
t5_mesh_transformer  \
	  --tpu="${TPU_NAME}" \
	  --gcp_project="${PROJECT}" \
	  --tpu_zone="${ZONE}" \
	  --model_dir="${MODEL_DIR}" \
	  --t5_tfds_data_dir="${DATA_DIR}" \
	  --gin_file="dataset.gin" \
	  --gin_file="models/bi_v1.gin" \
	  --gin_param="utils.tpu_mesh_shape.model_parallelism = 1" \
	  --gin_param="utils.tpu_mesh_shape.tpu_topology = '16x16'" \
	  --gin_param="MIXTURE_NAME = 'glue_mrpc_v002'"

>Did you just copy/paste from the "Training" section you linked?

in common, yes, I copy-pasted and changed 1 parameter:
`--gin_param="utils.tpu_mesh_shape.tpu_topology = '16x16'"`

>Was your model directory empty before you started training?
yes

>The links are still 404 for me.

below all stdout as well as stderr:
[nan-loss.log](https://github.com/google-research/text-to-text-transfer-transformer/files/4776967/nan-loss.log)

**Comment by craffel** [comment]
Ok. Assuming that your T5 and Mesh TF library code (and gin files etc) are completely unmodified, my best guess is that this is because you are effectively using a batch parallelism of 512 (because of no model parallelism on a 16x16 slice) and I think the batch size is probably defaulting to 1024 tokens per batch: https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/mtf_model.py#L73 which would be 2 sequences per batch. I would have thought this would have caused an exception but I guess it is NaNing. Maybe try setting `  --gin_param="utils.run.batch_size = (\"tokens_per_batch\", 1048576)"  \` or some other big value and see if that NaNs. You also may want to use a bigger dataset than MRPC in case it is repeating data and that is causing a NaN.

Separately, note that you will not get huge speedups beyond maybe a 4x4 TPU with the "base" sized model (bi_v1.gin) because you will be data bottlenecked. But, at least it should not NaN.

**Comment by craffel** [comment]
Is this fixed?

**Comment by orsk-moscow** [comment]
Hi, @craffel . Unfortunately, I can not reproduce the same experiment because of I do not have such powerful TPU more.

**Comment by craffel** [comment]
Ok, please re-open if you encounter this issue again.

**Comment by agemagician** [comment]
I had also "Nan" problem when I trained the 11B model using TPU V3-512 on my own custom dataset.
In my case, the issue was the LR. the default initial LR when using 10k warmup is 0.01.
I had to increase the warmup to 40k, which reduced the initial LR to 0.005.
Afterward, everything was running fine.

**Comment by craffel** [comment]
Thanks for sharing. @orsk-moscow feel free to try this if/when you try 11B training again.
