### ISSUE TITLE
ValueError: Provider name not registered: glue_ax_v002

### ISSUE THREAD

**Issue by SungjoonPark** [google-research/text-to-text-transfer-transformer#341]
I'm getting following error while importing t5:

>>> import t5
INFO:tensorflow:tokens_length=568 inputs_length=512 targets_length=114 noise_density=0.15 mean_noise_span_length=3.0 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/t5/__init__.py", line 17, in <module>
    import t5.data
  File "/opt/conda/lib/python3.7/site-packages/t5/data/__init__.py", line 17, in <module>
    import t5.data.mixtures
  File "/opt/conda/lib/python3.7/site-packages/t5/data/mixtures.py", line 98, in <module>
    _glue_tasks_with_weight)
  File "/opt/conda/lib/python3.7/site-packages/t5/data/utils.py", line 1156, in add
    super(MixtureRegistry, cls).add(name, Mixture, tasks, default_rate)
  File "/opt/conda/lib/python3.7/site-packages/t5/data/utils.py", line 107, in add
    provider = provider_cls(*provider_args, **provider_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/t5/data/utils.py", line 945, in __init__
    self._tasks.append(TaskRegistry.get(task_name))
  File "/opt/conda/lib/python3.7/site-packages/t5/data/utils.py", line 126, in get
    raise ValueError("Provider name not registered: %s" % name)
ValueError: Provider name not registered: glue_ax_v002

I've installed all dependencies for t5, any ideas why I am failing to import the package?

Thanks.

**Comment by SungjoonPark** [comment]
I found the reason. If the version of tfds is low (1.x.x) 'ax' dataset is missing in GLUE benckmark, leads to missing keys in _glue_tasks_with_weight. Upgrading tensorflow_datasets resoloved the issue.
