### ISSUE TITLE
ERROR: ... does not exist in any of the task cache directories 

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#350]
I have added [your provided `Task` definitions for NQ-open](https://github.com/google-research/google-research/blob/master/t5_closed_book_qa/t5_cbqa/tasks.py#L84-L96) to my code, like this: 

```python 
    t5.data.TaskRegistry.add(
        "natural_questions_open",
        TfdsTask,
        tfds_name="natural_questions:0.0.2",
        splits={
            "train": "train[7830:]",
            "validation": "train[:7830]",
            "test": "validation"
        },
        text_preprocessor=preprocess_natural_questions_open,
        postprocess_fn=t5_postprocessors.qa,
        sentencepiece_model_path=t5.data.DEFAULT_SPM_PATH,
        metric_fns=[t5_metrics.squad],
        supports_caching=False,
    )
```

I am getting the following error while trying to fine-tune with this task: 
```
ERROR:tensorflow:Error recorded from training_loop: 'natural_questions_open' does not exist in any of the task cache directories
  In call to configurable 'mesh_train_dataset_fn' (<function mesh_train_dataset_fn at 0x7f50c85ec7a0>)
```

My understanding is that these external datasets loaded from `TfdsTask` need to be cached (according to [the readme](https://github.com/google-research/text-to-text-transfer-transformer#tfdstask)). So tried to add the equivalent of `--t5_tfds_data_dir="${DATA_DIR}" ` to my code: 
```
t5.data.set_tfds_data_dir_override(f"gs://{bucket_name}/tfds_data_dir")
t5.data.add_global_cache_dirs(f"gs://{bucket_name}/tfds_data_dir")
```
However, the error has remained the same. Any thoughts what I am doing wrong? 

Here is the full error trace: 
```
2020-08-16 23:58:45.541278: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:370] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because
 the session has not yet been created.
WARNING:tensorflow:From /home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from t
ensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From /home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from t
ensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From /home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/training/training_util.py:236: Variable.initialized_value (from tensorflow.pytho
n.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
WARNING:tensorflow:From /home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/training/training_util.py:236: Variable.initialized_value (from tensorflow.pytho
n.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
ERROR:tensorflow:Error recorded from training_loop: 'natural_questions_open' does not exist in any of the task cache directories
  In call to configurable 'mesh_train_dataset_fn' (<function mesh_train_dataset_fn at 0x7fb93836b7a0>)
ERROR:tensorflow:Error recorded from training_loop: 'natural_questions_open' does not exist in any of the task cache directories
  In call to configurable 'mesh_train_dataset_fn' (<function mesh_train_dataset_fn at 0x7fb93836b7a0>)
WARNING:tensorflow:Reraising captured error
WARNING:tensorflow:Reraising captured error
Traceback (most recent call last):
  File "fine-tune-model.py", line 64, in <module>
    finetune_steps=finetune_steps
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/t5/models/mtf_model.py", line 295, in finetune
    split=split)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/t5/models/mtf_model.py", line 237, in train
    steps, self._ensemble_inputs, dataset_split=split)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1498, in train_model
    estimator.train(input_fn=input_fn, max_steps=train_steps)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1191, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2857, in _call_model_fn
    config)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)  
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3148, in _model_fn
    input_holders.generate_infeed_enqueue_ops_and_dequeue_fn())
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1428, in generate_infeed_enqueue_ops_and_dequeue_fn
    self._invoke_input_fn_and_record_structure())
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1483, in _invoke_input_fn_and_record_structure
    num_hosts))
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1090, in generate_broadcast_enqueue_ops_fn
    inputs = _Inputs.from_input_fn(input_fn(user_context))
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3001, in _input_fn
    return input_fn(**kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1492, in input_fn
    dataset_split=dataset_split)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/t5/models/mesh_transformer.py", line 69, in mesh_train_dataset_fn
    sequence_length, split=dataset_split, use_cached=use_cached, shuffle=True)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/t5/data/utils.py", line 1020, in get_dataset
    for task in tasks]
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/t5/data/utils.py", line 1020, in <listcomp>
    for task in tasks]
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/t5/data/utils.py", line 701, in get_dataset
    ds = self._get_cached_dataset(split, shuffle)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/t5/data/utils.py", line 728, in _get_cached_dataset
    self.assert_cached()
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/t5/data/utils.py", line 635, in assert_cached
    "'%s' does not exist in any of the task cache directories" % self.name)
AssertionError: 'natural_questions_open' does not exist in any of the task cache directories
  In call to configurable 'mesh_train_dataset_fn' (<function mesh_train_dataset_fn at 0x7fb93836b7a0>)
```

I am running the code on a TPU and here are my versions: 
```
t5                       0.6.3                
tensorboard              1.15.0               
tensorflow               1.15.2               
tensorflow-datasets      2.1.0                
tensorflow-estimator     1.15.1               
tensorflow-metadata      0.21.1               
tensorflow-text          1.15.0    
```

**Comment by craffel** [comment]
Hi, you will get that error if you are passing `use_cached=True` (probably via gin) to `mesh_train_dataset_fn` or `mesh_eval_dataset_fn` but you have not cached the Task. I would check the gin flags/files you are passing to see if any of them set that value to True. It does not pertain to TFDS caching, it pertains to task caching (via https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/cache_tasks_main.py)
