### ISSUE TITLE
ValueError: `mesh_shape` must be a vector of size 4 with positive entries while using TPU

### ISSUE THREAD

**Issue by vkaul11** [google-research/text-to-text-transfer-transformer#353]
I checked https://github.com/google-research/text-to-text-transfer-transformer/issues/320 but I have tensorflow=2.2.0
but still I am getting a similar error. Is this something to do with my TPU?

```
Name: tensorflow
Version: 2.2.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0

vivek_kaul_apple_com@vivek-kaul-instance:~$ pip show t5
Name: t5
Version: 0.6.3
Summary: Text-to-text transfer transformer
Home-page: http://github.com/google-research/text-to-text-transfer-transformer
Author: Google Inc.
Author-email: no-reply@google.com
License: Apache 2.0
```

```
t5_mesh_transformer  --tpu=vivekkaul-tpu-v3-32-1  --gcp_project=info-intel-web-answers-q5loch  --tpu_zone=us-east1-d  --model_dir=gs://t5-data/pretrained_models/small  --gin_file="dataset.gin"  --gin_param="utils.tpu_mesh_shape.model_parallelism=1"  --gin_param="utils.tpu_mesh_shape.tpu_topology='v3-32'"  --gin_param="utils.run.train_dataset_fn=@t5.models.mesh_transformer.tsv_dataset_fn"  --gin_param="tsv_dataset_fn.filename='gs://permanent-us-east1-q5loch/vivek-kaul-t5-data/NER_data_0_train.tsv'"  --gin_file="gs://t5-data/pretrained_models/small/operative_config.gin"  --gin_param="run.train_steps=1001000"  --gin_file="learning_rate_schedules/constant_0_001.gin"

INFO:tensorflow:Calling model_fn.
I0818 22:28:40.130470 138082487072512 estimator.py:1162] Calling model_fn.
/home/haitong_apple_com/.local/lib/python3.6/site-packages/mesh_tensorflow/transformer/dataset.py:271: UserWarning: Creating resources inside a function passed to Dataset.map() is not supported. Create each resource outside the function, and capture it inside the function to use it.
  _encode_fn, num_parallel_calls=tf.data.experimental.AUTOTUNE)
2020-08-18 22:28:41.347031: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-08-18 22:28:41.347080: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-08-18 22:28:41.347112: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (vivek-kaul-instance): /proc/driver/nvidia/version does not exist
INFO:tensorflow:training_loop marked as finished
I0818 22:28:41.750122 138082487072512 error_handling.py:115] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0818 22:28:41.750385 138082487072512 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "/home/haitong_apple_com/.local/bin/t5_mesh_transformer", line 8, in <module>
    sys.exit(console_entry_point())
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/t5/models/mesh_transformer_main.py", line 259, in console_entry_point
    app.run(main)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/t5/models/mesh_transformer_main.py", line 253, in main
    model_dir=FLAGS.model_dir)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/mesh_tensorflow/transformer/utils.py", line 2115, in run
    train_dataset_fn, train_steps, ensemble_inputs)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/mesh_tensorflow/transformer/utils.py", line 1498, in train_model
    estimator.train(input_fn=input_fn, max_steps=train_steps)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3089, in train
    rendezvous.raise_errors()
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3084, in train
    saving_listeners=saving_listeners)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, in _train_model_default
    self.config)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2921, in _call_model_fn
    config)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3201, in _model_fn
    input_holders.generate_infeed_enqueue_ops_and_dequeue_fn())
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1465, in generate_infeed_enqueue_ops_and_dequeue_fn
    self._invoke_input_fn_and_record_structure())
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1528, in _invoke_input_fn_and_record_structure
    enqueue_ops.append(wrap_fn(device=host_device, op_fn=enqueue_ops_fn))
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3719, in _wrap_computation_in_while_loop
    parallel_iterations=1)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2774, in while_loop
    return_same_structure)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2256, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2181, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3708, in computation
    with tf.control_dependencies(op_fn()):
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1200, in enqueue_ops_fn
    placement_function=device_function_impl)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow/python/tpu/tpu_feed.py", line 611, in generate_enqueue_ops
    for (shard, index) in zip(sharded_inputs, xrange(self.number_of_shards))
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow/python/tpu/tpu_feed.py", line 611, in <listcomp>
    for (shard, index) in zip(sharded_inputs, xrange(self.number_of_shards))
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1145, in tpu_ordinal_function_impl
    if ctx.device_assignment:
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 357, in device_assignment
    if self._model_parallelism_enabled else None)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 299, in _get_device_assignment
    num_replicas=self.num_replicas)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow/python/tpu/device_assignment.py", line 358, in device_assignment
    topology = Topology(serialized=topology)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow/python/tpu/topology.py", line 80, in __init__
    self._parse_topology(serialized)
  File "/home/haitong_apple_com/.local/lib/python3.6/site-packages/tensorflow/python/tpu/topology.py", line 111, in _parse_topology
    "entries; got {}".format(self._mesh_shape))
ValueError: `mesh_shape` must be a vector of size 4 with positive entries; got [4 4 2]
  In call to configurable 'run' (<function run at 0x7d9576c89598>)
```

**Comment by sharannarang** [comment]
You may want to check the TPU software version. I was getting this error when the tpu version was 2.3 with tensorflow 2.2. 

With tpu s/w version = 2.3 and tensorflow 2.3, I don't see this error anymore.

**Comment by vkaul11** [comment]
How do you check TPU version ?

**Comment by vkaul11** [comment]
My TPU version is tf 2.2 and looks like t5 also has tf 2.2. Is this problem different ?

**Comment by sharannarang** [comment]
I'd suggest switching to tf 2.3 with the same tpu version since it has been working reliably for me.

**Comment by vkaul11** [comment]
Thanks that worked.
