### ISSUE TITLE
model.fine_tune does not work ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable

### ISSUE THREAD

**Issue by vkaul11** [google-research/text-to-text-transfer-transformer#363]
I was using a code similar to what is given in the notebook but for some reason the fine-tune task does not work for me

```
ner_task = t5.data.TaskRegistry.get("ner_data")
ds = ner_task.get_dataset(split="validation", sequence_length={"inputs": 128, "targets": 32})
print("A few preprocessed validation examples...")
for ex in tfds.as_numpy(ds.take(5)):
  print(ex)

TPU_ADDRESS="vivek_kaul_tpu"
MODEL_SIZE = "small" #@param["small", "base", "large", "3B", "11B"]
# Public GCS path for T5 pre-trained model checkpoints
BASE_PRETRAINED_DIR = "gs://permanent-us-east1-q5loch/t5-models/pretrained_models"
PRETRAINED_DIR = os.path.join(BASE_PRETRAINED_DIR, MODEL_SIZE)
#MODEL_DIR = os.path.join(MODELS_DIR, MODEL_SIZE)

# Limit number of checkpoints to fit within 5GB (if possible).
model_parallelism, train_batch_size, keep_checkpoint_max = {
    "small": (1, 256, 16),
    "base": (2, 128, 8),
    "large": (8, 64, 4),
    "3B": (8, 16, 1),
    "11B": (8, 16, 1)}[MODEL_SIZE]

print(MODELS_DIR)
#tf.io.gfile.makedirs(MODEL_DIR)
# The models from our paper are based on the Mesh Tensorflow Transformer.
model = t5.models.MtfModel(
    model_dir=MODELS_DIR,
    tpu=TPU_ADDRESS,
    tpu_topology=TPU_TOPOLOGY,
    gcp_project="info-intel-web-answers-q5loch",
    tpu_zone="us-east1-d",
    model_parallelism=model_parallelism,
    batch_size=train_batch_size,
    sequence_length={"inputs": 128, "targets": 32},
    learning_rate_schedule=0.003,
    save_checkpoints_steps=5000,
    keep_checkpoint_max=keep_checkpoint_max,
    iterations_per_loop=100,
)

 #@param {type: "integer"}

model.finetune(
    mixture_or_task_name="ner_data",
    pretrained_model_dir=PRETRAINED_DIR,
    finetune_steps=1000
)
```

I get this error which points to **finetune_steps parameter** and I have no idea why this will be the case
```
WARNING:tensorflow:Using default tf glorot_uniform_initializer for variable encoder/block_000/layer_000/SelfAttention/relative_attention_bias  The initialzer will guess the input and output dimensions  based on dimension order.
WARNING:tensorflow:Using default tf glorot_uniform_initializer for variable decoder/block_000/layer_000/SelfAttention/relative_attention_bias  The initialzer will guess the input and output dimensions  based on dimension order.
INFO:tensorflow:Create pnum_tensor
INFO:tensorflow:training_loop marked as finished
WARNING:tensorflow:Reraising captured error
Traceback (most recent call last):
  File "t5/data/tasks_NER.py", line 122, in <module>
    finetune_steps=1000
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/t5/models/mtf_model.py", line 295, in finetune
    split=split)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/t5/models/mtf_model.py", line 237, in train
    steps, self._ensemble_inputs, dataset_split=split)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/mesh_tensorflow/transformer/utils.py", line 1498, in train_model
    estimator.train(input_fn=input_fn, max_steps=train_steps)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3089, in train
    rendezvous.raise_errors()
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3084, in train
    saving_listeners=saving_listeners)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, in _train_model_default
    self.config)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2921, in _call_model_fn
    config)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3212, in _model_fn
    _train_on_tpu_system(ctx, model_fn_wrapper, dequeue_fn))
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3654, in _train_on_tpu_system
    device_assignment=ctx.device_assignment)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/tpu/tpu.py", line 1665, in split_compile_and_shard
    name=name)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/tpu/tpu.py", line 1380, in split_compile_and_replicate
    outputs = computation(*computation_inputs)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3640, in multi_tpu_train_steps_on_single_shard
    inputs=[0, _INITIAL_LOSS])
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/tpu/training_loop.py", line 178, in while_loop
    condition_wrapper, body_wrapper, inputs, name="", parallel_iterations=1)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2696, in while_loop
    back_prop=back_prop)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/ops/while_v2.py", line 196, in while_loop
    add_control_dependencies=add_control_dependencies)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/ops/while_v2.py", line 174, in wrapped_body
    outputs = body(*_pack_sequence_as(orig_loop_vars, args))
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/tpu/training_loop.py", line 121, in body_wrapper
    outputs = body(*(inputs + dequeue_ops))
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3639, in <lambda>
    lambda i, loss: [i + 1, single_tpu_train_step(i)],
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1753, in train_step
    self._call_model_fn(features, labels))
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2031, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/mesh_tensorflow/transformer/utils.py", line 672, in my_model_fn
    log_file=model_info_file)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/mesh_tensorflow/ops.py", line 726, in __init__
    op.lower(self)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/mesh_tensorflow/ops.py", line 4038, in lower
    sv = mesh_impl.LaidOutVariable(self, mesh_impl)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/mesh_tensorflow/simd_mesh_impl.py", line 188, in __init__
    expected_shape=slice_shape)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 221, in _variable_v1_call
    shape=shape)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2597, in default_variable_creator
    shape=shape)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1518, in __init__
    distribute_strategy=distribute_strategy)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1601, in _init_from_args
    raise ValueError("Tensor-typed variable initializers must either be "
ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions. Please file a feature request if this restriction inconveniences you.

```

**Comment by vkaul11** [comment]
After using tf.disable_v2_behavior() this issue goes away.
