### ISSUE TITLE
Export a savedModel

### ISSUE THREAD

**Issue by qguo96** [google-research/text-to-text-transfer-transformer#461]
Hello, I tried to export a saveModel to my project and I followed the instruction and t5-deploy notebook.
```
MODEL = "t5.1.1.small_ssm_nq"

t5_mesh_transformer \
  --model_dir="gs://t5-data/pretrained_models/cbqa/{MODEL}" \
  --use_model_api \
  --mode="export_predict" \
  --export_dir="/path/to/export/dir"
```

I kept getting this error.
```
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-10-21 20:02:04.834682: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.
2020-10-21 20:02:04.872597: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.
2020-10-21 20:02:04.921189: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.
2020-10-21 20:02:04.961682: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.
2020-10-21 20:02:05.006856: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.
2020-10-21 20:02:05.050128: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.
2020-10-21 20:02:05.093726: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.
2020-10-21 20:02:05.169381: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.
I1021 20:02:05.219536 140030978254720 mesh_transformer_main.py:158] No write access to model directory. Skipping command logging.
2020-10-21 20:02:05.233245: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.
2020-10-21 20:02:05.278102: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.
2020-10-21 20:02:05.290531: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.
2020-10-21 20:02:05.339158: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.
2020-10-21 20:02:05.389949: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.
Traceback (most recent call last):
  File "/usr/local/bin/t5_mesh_transformer", line 8, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python3.6/dist-packages/t5/models/mesh_transformer_main.py", line 261, in console_entry_point
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/t5/models/mesh_transformer_main.py", line 239, in main
    score_mode=(FLAGS.mode == "export_score"))
  File "/usr/local/lib/python3.6/dist-packages/t5/models/mtf_model.py", line 470, in export
    vocabulary = _get_vocabulary()
  File "/usr/local/lib/python3.6/dist-packages/t5/models/mtf_model.py", line 68, in _get_vocabulary
    return t5.models.mesh_transformer.get_vocabulary(mixture_or_task_name)
  File "/usr/local/lib/python3.6/dist-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.6/dist-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/t5/models/mesh_transformer.py", line 213, in get_vocabulary
    provider = t5.data.get_mixture_or_task(mixture_or_task_name)
  File "/usr/local/lib/python3.6/dist-packages/t5/data/dataset_providers.py", line 1054, in get_mixture_or_task
    task_or_mixture_name)
ValueError: No Task or Mixture found with name: natural_questions_open_test
  In call to configurable 'get_vocabulary' (<function get_vocabulary at 0x7f5b23f25730>)
```

How can I solve this? Thank you!

**Comment by adarob** [comment]
We should probably make it fall back to the default if it can't find the task.

However, for now you should just follow the instructions of https://github.com/google-research/google-research/tree/master/t5_closed_book_qa.  You can clone that repo, go that folder, and run this command:

```
python -m t5.models.mesh_transformer_main \
  --module_import="t5_cbqa.tasks" \
  --model_dir="gs://t5-data/pretrained_models/cbqa/{MODEL}" \
  --use_model_api \
  --mode="export_predict" \
  --export_dir="/path/to/export/dir"
```
