### ISSUE TITLE
Manual download of common crawl WET files required before C4 apache beam dataflow job?

### ISSUE THREAD

**Issue by chrisrytting** [google-research/text-to-text-transfer-transformer#468]
I have been having serious trouble executing the simple instructions for downloading C4. After (1) running into quota issues then getting increases, then (2) successfully having the job run for several hours and then crash with an abstruse bug (`TypeError: clean_page() got an unexpected keyword argument 'badwords_regex' [while running 'clean_pages']`), which might have been a dependency error so I created a new virtual environment to try everything from scratch, (3) I got this error when starting the job.

```
AssertionError: Manual directory gs://create-c4/tensorflow_datasets/downloads/manual does not exist or is empty. Create it and download/extract dataset artifacts in there using instructions:
For the WebText-like config, you must manually download 'OpenWebText.zip'
(from https://mega.nz/#F!EZZD0YwJ!9_PlEQzdMVLaNdKv_ICNVQ) and the Common Crawl
WET files from August 2018 to July 2019
(https://commoncrawl.org/the-data/get-started/) and place them in the
`manual_dir`.
```

I didn't run into this error before, and the need to manually download the 7TB of Common Crawl WET files and the OpenWebText.zip file isn't mentioned in the instructions here. The need to do this IS mentioned in the [tfds c4 homepage](https://www.tensorflow.org/datasets/catalog/c4#c4en_default_config), however, and I'm wondering whether this manual download really is necessary?

**Comment by adarob** [comment]
Sorry Chris, I recently refactored to add multilingual C4 (mC4).
What config are you trying to build? You shouldn't need any manual downloads for `c4/en`.

**Comment by chrisrytting** [comment]
Trying to build `c4/en`. The command I run is

```
python -m tensorflow_datasets.scripts.download_and_prepare \
  --datasets=c4/en \
  --data_dir=gs://$MY_BUCKET/tensorflow_datasets \
  --beam_pipeline_options="project=$MY_PROJECT,job_name=c4,staging_location=gs://$MY_BUCKET/binaries,temp_location=gs://$MY_BUCKET/temp,runner=DataflowRunner,requirements_file=/tmp/beam_requirements.txt,experiments=shuffle_mode=service,region=$MY_REGION,max_num_workers=448,worker_machine_type=e2-standard-32"
```

**Comment by adarob** [comment]
Yeah, you definitely should not have to do any manual downloads for that, so it is a bug. I will do my best to look into it tonight. You could also go back to an older version.

**Comment by adarob** [comment]
Can you try creating gs://create-c4/tensorflow_datasets/downloads/manual and leaving it empty?

**Comment by adarob** [comment]
@Conchylicultor does having MANUAL_DOWNLOAD_INSTRUCTIONS require the manual dir exist even for configs that don't use it?

**Comment by adarob** [comment]
I see the problematic line now, but I think adding that empty dir will fix your issue for now.

**Comment by chrisrytting** [comment]
I actually already tried that and it still throws the AssertionError.

Do you have an idea of what a stable version would be? The instructions have us use `tfds-nightly`, which I take to mean updated every night, and I wonder if these instructions were written for a specific version, because as I said above, before I updated to the latest version of `tfds-nightly` and ran into this bug, I had run into the `TypeError: clean_page() got an unexpected keyword argument 'badwords_regex' [while running 'clean_pages']` issue, which I don't know if is a bug or my fault, and I have no idea where to start debugging the apache beam pipeline. I have just been assuming it would be clear what I needed to change beyond the simple instructions here (as it was with the quotas, for example).

**Comment by adarob** [comment]
Try adding an empty file in there as well. I think that will allow it to pass.

**Comment by adarob** [comment]
I just submitted https://github.com/tensorflow/datasets/pull/2638/commits/ff3076c926e46caa12724d693c4add7c5688722e and updated tfds-nightly, which should fix the manual dir issue. 

The clean_pages bug sounds like your workers and manager VMs have different versions of tfds. I think you just got unlucky and the workers picked up the version after the refactor while your manager had the older one. If you upgrade your manager, I think it will work now.

**Comment by chrisrytting** [comment]
Thanks for your help! I'll try this out tomorrow.

**Comment by chrisrytting** [comment]
@adarob after updating tfds-nightly to the latest version, I get this error right at the beginning of the job:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dataflow_worker/batchworker.py", line 649, in do_work
    work_executor.execute()
  File "/usr/local/lib/python3.6/site-packages/dataflow_worker/executor.py", line 179, in execute
    op.start()
  File "dataflow_worker/native_operations.py", line 38, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 39, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 44, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 54, in dataflow_worker.native_operations.NativeReadOperation.start
  File "apache_beam/runners/worker/operations.py", line 356, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 218, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 703, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 704, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1215, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1279, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1213, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 742, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 865, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "apache_beam/runners/common.py", line 1374, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 218, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 703, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 704, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1215, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1294, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "/usr/local/lib/python3.6/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "apache_beam/runners/common.py", line 1213, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 569, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1347, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "/mnt/pccfs/backed_up/crytting/persuasion/createc4/lib/python3.6/site-packages/tensorflow_datasets/core/tfrecords_writer.py", line 333, in _get_boundaries_per_bucket_shard
    raise AssertionError("Not a single example present in the PCollection!")
AssertionError: Not a single example present in the PCollection! [while running 'validation_write/GetBoundaries']
```

I deleted all the contents of my bucket from last month when I was running the job I mentioned in this issue, updated my manager, and can't find info on this error. Any idea on what I should do?

**Comment by vkaul11** [comment]
Is this issue fixed ?

**Comment by chrisrytting** [comment]
Not for me. With a newer version of tfds-nightly, tensorflow, pip, apache-beam, my job crashes with a different error before I get to the above stack trace, so I don't know whether this issue is fixed or not yet. The new issue I'm facing is in tensorflow datasets issue tracker [here](https://github.com/tensorflow/datasets/issues/2827#issue-756641297).
