### ISSUE TITLE
error using hf_model 

### ISSUE THREAD

**Issue by juliahane** [google-research/text-to-text-transfer-transformer#476]
Hi 
I am trying to call hf_model

```
import functools
import t5
import torch
import transformers
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
path = "/home/danielk/small_standard/pytorch_model/"
model = t5.models.HfPyTorchModel(path, path, device)
# Generate some predictions
inputs = [
    "Who is the US president? ",
    "How many states are there in USA? ",
    "who got the first nobel prize in physics?",
    "when is the next deadpool movie being released?",
    "which mode is used for short wave broadcast service?"
]
model.predict(
    inputs,
    sequence_length={"inputs": 32},
    batch_size=2,
    output_file=f"{path}/example_predictions.txt",
)
print("done making the predictions . . . ")
```

Here is the error stack
```
2020-10-24 18:52:52.491064: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/local/cuda/extras/CUPTI/lib64
2020-10-24 18:52:52.491107: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-10-24 18:53:00.010549: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-10-24 18:53:00.010840: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-24 18:53:00.011774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2020-10-24 18:53:00.011981: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/local/cuda/extras/CUPTI/lib64
2020-10-24 18:53:00.012145: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/local/cuda/extras/CUPTI/lib64
2020-10-24 18:53:00.012239: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-10-24 18:53:00.012310: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-10-24 18:53:00.015081: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-10-24 18:53:00.015251: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/local/cuda/extras/CUPTI/lib64
2020-10-24 18:53:00.015398: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/local/cuda/extras/CUPTI/lib64
2020-10-24 18:53:00.015429: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-10-24 18:53:00.015882: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-24 18:53:00.022658: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2000155000 Hz
2020-10-24 18:53:00.023679: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55a42ff6af40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-24 18:53:00.023715: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-24 18:53:00.025915: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-24 18:53:00.025949: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      
Traceback (most recent call last):
  File "example.py", line 47, in <module>
    output_file=f"example_predictions.txt",
  File "/opt/conda/lib/python3.7/site-packages/t5/models/hf_model.py", line 549, in predict
    num_parallel_calls=t5.data.preprocessors.num_parallel_calls()
  File "/opt/conda/lib/python3.7/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/opt/conda/lib/python3.7/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/opt/conda/lib/python3.7/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/t5/data/preprocessors.py", line 2692, in num_parallel_calls
    raise NotImplementedError('`num_paralell_calls` is deprecated. Do not use.')
NotImplementedError: `num_paralell_calls` is deprecated. Do not use.
  In call to configurable 'num_parallel_calls' (<function num_parallel_calls at 0x7fbe86ad9170>)
```

**Comment by juliahane** [comment]
could you please help me?

**Comment by juliahane** [comment]
I commented out num_parallel_call and then I ran into this issue, I greatly appreciate assisting me to run this example:

```
2020-10-24 19:13:09.695861: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/local/cuda/extras/CUPTI/lib64
2020-10-24 19:13:09.695918: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/opt/conda/envs/ruse/lib/python3.7/site-packages/t5/models/hf_model.py", line 88, in <module>
    import mesh_tensorflow.transformer.dataset as transformer_dataset
  File "/opt/conda/envs/ruse/lib/python3.7/site-packages/mesh_tensorflow/__init__.py", line 22, in <module>
    from mesh_tensorflow import beam_search
  File "/opt/conda/envs/ruse/lib/python3.7/site-packages/mesh_tensorflow/beam_search.py", line 87, in <module>
    @gin.configurable
AttributeError: module 'gin' has no attribute 'configurable'
```

**Comment by juliahane** [comment]
I also got this warning, could you please assist me with updating t5 minimally making this example work. thanks 

UserWarning: Creating resources inside a function passed to Dataset.map() is not supported. Create each resource outside the function, and capture it inside the function to use it.

**Comment by craffel** [comment]
The `num_parallel_calls` error should be fixed when installing from the latest code on github: `pip install git+https://github.com/google-research/text-to-text-transfer-transformer.git` 
The warning you can ignore.

**Comment by Huagela** [comment]
> I commented out num_parallel_call and then I ran into this issue, I greatly appreciate assisting me to run this example:
> 
> ```
> 2020-10-24 19:13:09.695861: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/local/cuda/extras/CUPTI/lib64
> 2020-10-24 19:13:09.695918: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> Traceback (most recent call last):
>   File "/opt/conda/envs/julia/lib/python3.7/site-packages/t5/models/hf_model.py", line 88, in <module>
>     import mesh_tensorflow.transformer.dataset as transformer_dataset
>   File "/opt/conda/envs/julia/lib/python3.7/site-packages/mesh_tensorflow/__init__.py", line 22, in <module>
>     from mesh_tensorflow import beam_search
>   File "/opt/conda/envs/julia/lib/python3.7/site-packages/mesh_tensorflow/beam_search.py", line 87, in <module>
>     @gin.configurable
> AttributeError: module 'gin' has no attribute 'configurable'
> ```



> I commented out num_parallel_call and then I ran into this issue, I greatly appreciate assisting me to run this example:
> 
> ```
> 2020-10-24 19:13:09.695861: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/local/cuda/extras/CUPTI/lib64
> 2020-10-24 19:13:09.695918: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> Traceback (most recent call last):
>   File "/opt/conda/envs/julia/lib/python3.7/site-packages/t5/models/hf_model.py", line 88, in <module>
>     import mesh_tensorflow.transformer.dataset as transformer_dataset
>   File "/opt/conda/envs/julia/lib/python3.7/site-packages/mesh_tensorflow/__init__.py", line 22, in <module>
>     from mesh_tensorflow import beam_search
>   File "/opt/conda/envs/julia/lib/python3.7/site-packages/mesh_tensorflow/beam_search.py", line 87, in <module>
>     @gin.configurable
> AttributeError: module 'gin' has no attribute 'configurable'
> ```

same error :
`AttributeError: module 'gin' has no attribute 'configurable'`
