### ISSUE TITLE
training hf_model as script provided gives several errors 

### ISSUE THREAD

**Issue by juliahane** [google-research/text-to-text-transfer-transformer#477]
Hi,
I followed the training script given on top of hf_model, I am getting these errors, I really appreciate assisting me to train this model 

```
Traceback (most recent call last):
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow_datasets/core/download/checksums.py", line 154, in _parse_url_infos
    url, size, checksum = line.split('\t')
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 14, in <module>
    batch_size=128,
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/t5/models/hf_model.py", line 411, in eval
    ds = get_dataset(task.name, sequence_length, split, batch_size)
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/t5/models/hf_model.py", line 150, in get_dataset
    ds = task.get_dataset(sequence_length, split)
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/t5/data/dataset_providers.py", line 516, in get_dataset
    ds = self._dataset_fn(split=split, shuffle_files=shuffle)
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/t5/data/dataset_providers.py", line 633, in dataset_fn
    split, shuffle_files, seed=seed)
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/t5/data/utils.py", line 142, in load
    read_config=tfds.ReadConfig(shuffle_seed=seed))
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow_datasets/core/load.py", line 344, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 372, in download_and_prepare
    download_config=download_config)
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 798, in _make_download_manager
    register_checksums=download_config.register_checksums,
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py", line 211, in __init__
    self._url_infos = checksums.get_all_url_infos()
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow_datasets/core/download/checksums.py", line 172, in get_all_url_infos
    dataset_url_infos = _get_url_infos(path)
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow_datasets/core/download/checksums.py", line 143, in _get_url_infos
    return _parse_url_infos(content.splitlines())
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow_datasets/core/download/checksums.py", line 157, in _parse_url_infos
    url, size, checksum = line.rsplit(' ', 2)
ValueError: not enough values to unpack (expected 3, got 1)
```

Here is the training command:
```
import functools
import t5
import torch
import transformers
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
model = t5.models.HfPyTorchModel("t5-base", "/tmp/hft5/", device)
# Evaluate the pre-trained checkpoint, before further fine-tuning
model.eval(
    "glue_cola_v002",
    sequence_length={"inputs": 64, "targets": 4},
    batch_size=128,
)
# Run 1000 steps of fine-tuning
model.train(
    mixture_or_task_name="glue_cola_v002",
    steps=1000,
    save_steps=100,
    sequence_length={"inputs": 64, "targets": 4},
    split="train",
    batch_size=32,
    optimizer=functools.partial(transformers.AdamW, lr=1e-4),
)
# Evaluate after fine-tuning
model.eval(
    "glue_cola_v002",
    checkpoint_steps="all",
    sequence_length={"inputs": 64, "targets": 4},
    batch_size=128,
)
# Generate some predictions
inputs = [
    "cola sentence: This is a totally valid sentence.",
    "cola sentence: A doggy detail was walking famously.",
]
model.predict(
    inputs,
    sequence_length={"inputs": 32},
    batch_size=2,
    output_file="/tmp/hft5/example_predictions.txt",
)
```

**Comment by craffel** [comment]
Hi, this code is working fine when installed from source: https://colab.research.google.com/drive/1MNJVqfCqnaT2lb7IV87O1fPKWTwJansy?usp=sharing
The error you are seeing is in `tensorflow-datasets`. You may have an old version of `tensorflow-datasets` installed or something. I would suggest creating a new Python environment, running `pip install git+https://github.com/google-research/text-to-text-transfer-transformer.git` again (which will install the correct version of `tensorflow-datasets`), and trying again.
