### ISSUE TITLE
hf model example does not run 

### ISSUE THREAD

**Issue by juliahane** [google-research/text-to-text-transfer-transformer#478]
Hi,
I ran the example on top of hf model for running the model on pytorch, here is the stack errors, could you please assist me, thanks

/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import t5
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/t5/__init__.py", line 17, in <module>
    import t5.data
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/t5/data/__init__.py", line 17, in <module>
    from t5.data.dataset_providers import *  # pylint:disable=wildcard-import
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/t5/data/dataset_providers.py", line 30, in <module>
    from t5.data import utils
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/t5/data/utils.py", line 24, in <module>
    from t5.data import sentencepiece_vocabulary
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/t5/data/sentencepiece_vocabulary.py", line 23, in <module>
    from t5.data import vocabularies
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/t5/data/vocabularies.py", line 20, in <module>
    import tensorflow.compat.v2 as tf
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 83, in <module>
    from tensorflow.python import keras
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/keras/__init__.py", line 26, in <module>
    from tensorflow.python.keras import activations
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/keras/activations.py", line 24, in <module>
    from tensorflow.python.keras.utils.generic_utils import deserialize_keras_object
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/keras/utils/__init__.py", line 39, in <module>
    from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/keras/utils/multi_gpu_utils.py", line 22, in <module>
    from tensorflow.python.keras.engine.training import Model
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 40, in <module>
    from tensorflow.python.keras.engine import network
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 39, in <module>
    from tensorflow.python.keras import saving
  File "/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/keras/saving/__init__.py", line 33, in <module>
    from tensorflow.python.keras.saving.saved_model import export_saved_model
ImportError: cannot import name 'export_saved_model' from 'tensorflow.python.keras.saving.saved_model' (/opt/conda/envs/julia/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/__init__.py)

**Comment by craffel** [comment]
It looks like you are using an old or otherwise incorrect version of Tensorflow. Please create a clean Python environment and install t5 via pip; we have tested that this currently works fine.
