### ISSUE TITLE
`physical and logical shapes must have the same product`

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#488]
On a v3-8 TPU (software version 2.2), I am getting the following error: 

```
Traceback (most recent call last):
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 264, in <module>
    console_entry_point()
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 261, in console_entry_point
    app.run(main)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 255, in main
    model_dir=FLAGS.model_dir)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 2302, in run
    skip_seen_data=skip_seen_data)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1615, in train_model
    estimator.train(input_fn=input_fn, max_steps=train_steps)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1191, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2857, in _call_model_fn
    config)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3159, in _model_fn
    _train_on_tpu_system(ctx, model_fn_wrapper, dequeue_fn))
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3604, in _train_on_tpu_system
    device_assignment=ctx.device_assignment)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_core/python/tpu/tpu.py", line 1277, in split_compile_and_shard
    name=name)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_core/python/tpu/tpu.py", line 992, in split_compile_and_replicate
    outputs = computation(*computation_inputs)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3589, in multi_tpu_train_steps_on_single_shard
    inputs=[0, _INITIAL_LOSS])
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_core/python/tpu/training_loop.py", line 178, in while_loop
    condition_wrapper, body_wrapper, inputs, name="", parallel_iterations=1)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2753, in while_loop
    return_same_structure)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2245, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2170, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_core/python/tpu/training_loop.py", line 121, in body_wrapper
    outputs = body(*(inputs + dequeue_ops))
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3588, in <lambda>
    lambda i, loss: [i + 1, single_tpu_train_step(i)],
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1715, in train_step
    self._call_model_fn(features, labels))
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1994, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 388, in my_model_fn
    mesh_shape.to_integer_list, physical_shape)
  File "/home/danielk/anaconda3/envs/cbqa_py37/lib/python3.7/site-packages/mesh_tensorflow/simd_mesh_impl.py", line 864, in auto_logical_to_physical_tpu
    "physical_shape=%s logical_shape=%s" % (physical_shape, logical_shape))
ValueError: physical and logical shapes must have the same product physical_shape=[2, 2, 2] logical_shape=[32]
  In call to configurable 'run' (<function run at 0x7fe63e2f3f80>)
```

When running the following command: 
```
  python -m t5.models.mesh_transformer_main \
    --module_import="genie" \
    --tpu="${TPU_NAME}" \
    --gcp_project="${PROJECT}" \
    --tpu_zone="${ZONE}" \
    --model_dir="${MODEL_DIR}" \
    --gin_file="dataset.gin" \
    --gin_file="${PRETRAINED_DIR}/operative_config.gin" \
    --gin_param="utils.run.save_checkpoints_steps=1000" \
    --gin_param="utils.tpu_mesh_shape.tpu_topology = '2x2'" \
    --gin_param="MIXTURE_NAME = '${TASK}'" \
    --gin_param="utils.run.batch_size=('tokens_per_batch', 24576)" \
    --gin_param="utils.run.train_steps=$((PRETRAINED_STEPS + FINETUNE_STEPS))" \
    --gin_param="utils.run.init_checkpoint='${PRETRAINED_DIR}/model.ckpt-${PRETRAINED_STEPS}'" \
    --t5_tfds_data_dir="${BUCKET}/t5-tfds"
```

here are the parameters: 
```
t5                       0.7.1
tensorboard              1.15.0
tensorboard-plugin-wit   1.7.0
tensorflow               1.15.4
tensorflow-datasets      3.2.1
tensorflow-estimator     1.15.1
tensorflow-metadata      0.23.0
tensorflow-text          1.15.0
```

**Comment by craffel** [comment]
This means that the mesh layout determined by Mesh TensorFlow does not map onto the device you are training on (a v3-8). I am guessing the file "${PRETRAINED_DIR}/operative_config.gin" has model_parallelism > 8 (probably 32 based on that error message) or something, is that the case? This would mean that you are telling mesh to split up the model 32 ways on a device with only 8 cores, so it's complaining.

Looking forward to hearing more about genie :)

**Comment by danyaljj** [comment]
Got it, thank you! 🙏
