### ISSUE TITLE
Evaluating fine-tuned model is throwing error 

### ISSUE THREAD

**Issue by dpanshu** [google-research/text-to-text-transfer-transformer#514]
I trained a pre-trained T5 using similar code as trivia-qa notebook, however the evaluation part throws the following error 
```
INFO:tensorflow:Using config: {'_model_dir': 'models/small', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=100, num_shards=None, num_cores_per_replica=1, per_host_input_for_training=4, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None, eval_training_input_configuration=2, experimental_host_call_every_n_steps=1), '_cluster': None}
INFO:tensorflow:_TPUContext: eval_on_tpu True
WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in evaluate
  File "/miniconda/lib/python3.7/site-packages/t5/models/mtf_model.py", line 300, in eval
    eval_checkpoint_step=checkpoint_steps, eval_with_score=eval_with_score)
  File "/miniconda/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1731, in eval_model
    summary_writer = tf.summary.FileWriter(eval_summary_dir)
  File "/miniconda/lib/python3.7/site-packages/tensorflow/python/summary/writer/writer.py", line 360, in __init__
    "v1.summary.FileWriter is not compatible with eager execution. "
RuntimeError: v1.summary.FileWriter is not compatible with eager execution. Use `tf.summary.create_file_writer`,or a `with v1.Graph().as_default():` context
```

**Comment by adarob** [comment]
You'll need to run `tf.compat.v1.disable_v2_behavior()` for v1 summary to work.

**Comment by adarob** [comment]
@sharannarang will this be fixed with your changes?

**Comment by dpanshu** [comment]
That resolves it. Thanks

**Comment by sharannarang** [comment]
@adarob, yes, I think it'll be fixed with my changes.
