### ISSUE TITLE
Error when eval_with_score enabled

### ISSUE THREAD

**Issue by sarapapi** [google-research/text-to-text-transfer-transformer#534]
Hi!
I've tried to use your code from google colab but using GPUs instead and a custom dataset (English to German), training succeed but when I try to perform evaluation enabling `eval_with_score` it ends with these message:
`Traceback (most recent call last):
  File "T5google_evaluation.py", line 122, in <module>
    model.eval(
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/t5/models/mtf_model.py", line 295, in eval
    utils.eval_model(
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/mesh_tensorflow/transformer/utils.py", line 1788, in eval_model
    outputs, _ = _score_with_estimator(
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/mesh_tensorflow/transformer/utils.py", line 1254, in _score_with_estimator
    return score_postprocess_fn(results, vocabulary)
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/mesh_tensorflow/transformer/utils.py", line 1287, in save_scores
    targets = _maybe_decode_python(targets, targets_vocabulary(vocabulary))
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/mesh_tensorflow/transformer/utils.py", line 1309, in _maybe_decode_python
    ids_or_strs = [vocabulary.decode(t.tolist()) for t in ids_or_strs]
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/mesh_tensorflow/transformer/utils.py", line 1309, in <listcomp>
    ids_or_strs = [vocabulary.decode(t.tolist()) for t in ids_or_strs]
AttributeError: 'bytes' object has no attribute 'tolist'
  In call to configurable 'save_scores' (<function save_scores at 0x7f13f892f1f0>)`
Note that if `eval_with_score=False`, the evaluation succeed and the output files are saved.
Why does this happen?

**Comment by adarob** [comment]
@daphnei can you take a look?
