### ISSUE TITLE
Use exported T5 SavedModel in TensorFlow Java

### ISSUE THREAD

**Issue by maziyarpanahi** [google-research/text-to-text-transfer-transformer#551]
Hi,

I am planning to run some fine-tuning experiments, but before doing that I wanted to be sure I can use the SavedModel in TensorFlow Java which is only 1.15.0 at the moment.

To do a simple test, I used this [notebook](https://github.com/google-research/text-to-text-transfer-transformer/blob/master/notebooks/t5-deploy.ipynb) and exported `small_ssm_nq` model. Checking `saved_model_cli` I can see everything is normal to be served. However, when I try to load it in Java by using `SavedModelBundle.load` I get the following error ('ParallelMapDatasetV2'):

```
2020-11-29 20:12:15.377563: I tensorflow/cc/saved_model/loader.cc:311] SavedModel load for tags { serve }; Status: fail. Took 153238 microseconds.
Exception in thread "main" org.tensorflow.TensorFlowException: Op type not registered 'ParallelMapDatasetV2' in binary running on my_machine. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
	at org.tensorflow.SavedModelBundle.load(Native Method)
...
```

I wanted to ask for some help since I saw some history regarding `1.15.x` (mostly about TPU) and see if it was possible to load any T5 pretrained or fine-tuned models in TensorFlow Java (1.15.0) just for inferences.

**Comment by adarob** [comment]
What version of tf are you using when doing the export?

**Comment by maziyarpanahi** [comment]
Hi @adarob,

I used the latest 2.3 if I am not mistaken (the default that comes with Colab, same demo notebook for exporting models). I did try with TF 1.15.0 on Colab, however, there was this error when I executed the export:

```python
MODEL = "small_ssm_nq" 

import os

saved_model_dir = f"/content/{MODEL}"

!t5_mesh_transformer \
  --model_dir="gs://t5-data/pretrained_models/cbqa/{MODEL}" \
  --use_model_api \
  --mode="export_predict" \
  --export_dir="{saved_model_dir}"


```

```
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so.2: cannot open shared object file: No such file or directory
```

However, I didn't use any `tf.disable_v2_behavior()` as I've seen in another notebook. I used this notebook without any change: https://github.com/google-research/text-to-text-transfer-transformer/blob/master/notebooks/t5-deploy.ipynb

**Comment by adarob** [comment]
You should try doing `%tensorflow_version 1.x` before doing any imports.

**Comment by maziyarpanahi** [comment]
thanks @adarob 

I'll try it shortly and come back to you, many thanks.

**Comment by maziyarpanahi** [comment]
@adarob 
I have tried to export with `%tensorflow_version 1.x`, after trying to load it in Java, I am still seeing the same error. 
Just to be sure I am exporting it the right way for TF v1, here is the link to simple Colab:
https://colab.research.google.com/drive/1vfTGbbo_Ptg2dYiQXIQab4217upWyowO?usp=sharing

**Comment by adarob** [comment]
For the latest issue, you're seeing the error when you export the model or
when you load it?

**Comment by maziyarpanahi** [comment]
@adarob 

The export goes fine either with default TF V2 or as you suggested by using `tensorflow_version 1.x`. (no more error in export with this magic)

However, in both exported models (V2 and V1) I still have the following error in TensorFlow Java:
```
Exception in thread "main" org.tensorflow.TensorFlowException: Op type not registered 'ParallelMapDatasetV2' in binary
```

A little more observation on `tensorflow_version 1.x`:

When I use `tensorflow_version 1.x`, I no longer can load the saved model for prediction in the same notebook (works fine if TF is V2). I believe if the model is saved as TF 1.x one should use the following code to load the saved model:

```python
import tensorflow as tf

def load_predict_fn(model_path):
    print("Loading SavedModel in tf 1.x graph mode.")
    tf.compat.v1.reset_default_graph()
    sess = tf.compat.v1.Session()
    meta_graph_def = tf.compat.v1.saved_model.load(sess, ["serve"], model_path)
    signature_def = meta_graph_def.signature_def["serving_default"]
    return lambda x: sess.run(
        fetches=signature_def.outputs["outputs"].name, 
        feed_dict={signature_def.inputs["input"].name: x}
    )

predict_fn = load_predict_fn(saved_model_path)

```
But this gives an error of:

```
Loading SavedModel in tf 1.x graph mode.
WARNING:tensorflow:From <ipython-input-7-9b015c11eedd>:9: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-9b015c11eedd>", line 16, in <module>
    predict_fn = load_predict_fn(saved_model_path)
  File "<ipython-input-7-9b015c11eedd>", line 9, in load_predict_fn
    meta_graph_def = tf.compat.v1.saved_model.load(sess, ["serve"], model_path)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/util/deprecation.py", line 324, in new_func
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/saved_model/loader_impl.py", line 269, in load
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/saved_model/loader_impl.py", line 422, in load
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/saved_model/loader_impl.py", line 352, in load_graph
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 1477, in _import_meta_graph_with_return_elements
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/meta_graph.py", line 809, in import_scoped_meta_graph_with_return_elements
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/util/deprecation.py", line 507, in new_func
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'ParallelMapDatasetV2' in binary running on 0941b20ae214. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 1823, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NotFoundError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 1132, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 358, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.6/inspect.py", line 1490, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.6/inspect.py", line 1448, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.6/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.6/inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "/tensorflow-1.15.2/python3.6/tensorflow/__init__.py", line 50, in __getattr__
  File "/tensorflow-1.15.2/python3.6/tensorflow/__init__.py", line 44, in _load
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow_core.keras'
---------------------------------------------------------------------------```
```

I thought this might help since it happens in the Colab/Python to narrow down a solution for TensorFlow V1 in Java.

Thanks again @adarob for your help

**Comment by adarob** [comment]
Try doing also `!pip install "tensorflow<2"` after you install t5. I think
when you call the `t5_mesh_transformer` binary, it ignores the magic.

**Comment by maziyarpanahi** [comment]
Thanks @adarob, I've tried the following at the beginning:

```
!pip install -q t5
!pip install "tensorflow<2
```

Unfortunately, I still get the same error when I try to load the SavedModel in Python. Is it possible that the latest `t5` PyPI is only TF v2 compatible and not 1.15.x?

**Comment by maziyarpanahi** [comment]
@adarob 
I gave this a few more shots, but no matter what the `ParallelMapDatasetV2` ops is required in the exported model regardless of the TF version. 

Is `ParallelMapDatasetV2` really required for `inference`? I am assuming it's related to TF Datasets so it must be useful for the training and fine-tuning, but for the prediction can it be removed somehow before the export?

**Comment by adarob** [comment]
I think the only map comes in through this line: https://github.com/tensorflow/mesh/blob/83d1e0f8f7bdd088241e1d7c64a0d914f8ec0ad1/mesh_tensorflow/transformer/utils.py#L1985

You could potentially avoid a map if you remove this and pass in tokens directly.
