### ISSUE TITLE
Fine-Tuning T5 on GPU

### ISSUE THREAD

**Issue by pminervini** [google-research/text-to-text-transfer-transformer#654]
Hello, I'm trying to fine-tune T5 using the task available in https://github.com/google-research/google-research/tree/master/t5_closed_book_qa using the following command:

```bash
$ PYTHONPATH=. t5_mesh_transformer --model_dir=models \
    --gin_param="run.mesh_shape = 'model:1,batch:1'"  \
    --gin_param="utils.run.mesh_devices = ['gpu:0']" \
    --gin_param="MIXTURE_NAME = 'closed_book_qa'" \
    --module_import="t5_cbqa.tasks" \
    --gin_param="utils.run.save_checkpoints_steps=1000" \
    --gin_param="utils.run.batch_size=('tokens_per_batch', 196608)" \
    --gin_param="utils.run.train_steps=1110000" \
    --gin_param="utils.run.init_checkpoint='gs://t5-data/pretrained_models/cbqa/small_ssm/model.ckpt-1100000'" \
    --gin_param="utils.run.learning_rate_schedule=@learning_rate_schedules.constant_learning_rate" \
    --gin_param="constant_learning_rate.learning_rate=1e-3" \
    --gin_file="gs://t5-data/pretrained_models/cbqa/small_ssm/operative_config.gin"
```

And it's failing with the following message:

```
I0117 20:06:25.401206 4558376448 resource_reader.py:50] system_path_file_exists:gs://t5-data/pretrained_models/cbqa/small_ssm/operative_config.gin
E0117 20:06:25.402021 4558376448 resource_reader.py:55] Path not found: gs://t5-data/pretrained_models/cbqa/small_ssm/operative_config.gin
Traceback (most recent call last):
  File "/Users/pasquale/anaconda3/envs/cpu/bin/t5_mesh_transformer", line 8, in <module>
    sys.exit(console_entry_point())
  File "/Users/pasquale/anaconda3/envs/cpu/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 277, in console_entry_point
    app.run(main)
  File "/Users/pasquale/anaconda3/envs/cpu/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Users/pasquale/anaconda3/envs/cpu/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/pasquale/anaconda3/envs/cpu/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 172, in main
    gin.finalize()
  File "/Users/pasquale/anaconda3/envs/cpu/lib/python3.7/site-packages/gin/config.py", line 1924, in finalize
    new_bindings = hook(_CONFIG)
  File "/Users/pasquale/anaconda3/envs/cpu/lib/python3.7/site-packages/gin/config.py", line 2126, in find_unknown_references_hook
    _raise_unknown_reference_error(maybe_unknown, additional_msg)
  File "/Users/pasquale/anaconda3/envs/cpu/lib/python3.7/site-packages/gin/config.py", line 279, in _raise_unknown_reference_error
    raise ValueError(err_str.format(ref.selector, maybe_parens, additional_msg))
ValueError: No configurable matching reference '@t5.models.mesh_transformer.get_sentencepiece_model_path()'. In binding for 'SentencePieceVocabulary.sentencepiece_model_file'.
```

How would you recommend to sort this out?

**Comment by pminervini** [comment]
A temporary solution for me was reverting to `t5==0.7.1`

**Comment by craffel** [comment]
This issue persists.

**Comment by Xnhyacinth** [comment]
> This issue persists.

how to solve it?

**Comment by Xnhyacinth** [comment]
> A temporary solution for me was reverting to `t5==0.7.1`

when I install `t5==0.7.1`, however, the program does not report an error and gets stuck and cannot be terminated, so you have to kill or close the shell.

**Comment by pranavsenthil5** [comment]
@Xnhyacinth @pminervini @craffel How did you fix the issue?
