### ISSUE TITLE
help needed to debug ''could not parse rpc response" issue 

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#658]
Hey there! 👋 

I am getting getting "could not parse rpc response" message during a seemingly normal fine-tuning. 
Would appreciate it if you can share your thoughts in terms of solutions or effective ways to debug the issue. 

Here is the fine-tuning call: 
```
>     python -m t5.models.mesh_transformer_main \
      --module_import="harsht_protocol_comparison_task" \
      --tpu="${TPU_NAME}" \
      --gcp_project="${PROJECT}" \
      --tpu_zone="${ZONE}" \
      --model_dir="${MODEL_DIR}" \
      --gin_file="dataset.gin" \
      --gin_file="${PRETRAINED_DIR}/operative_config.gin" \
      --gin_param="utils.run.save_checkpoints_steps=1000" \
      --gin_param="utils.tpu_mesh_shape.tpu_topology = 'v3-128'" \
      --gin_param="MIXTURE_NAME = '${TASK}'" \
      --gin_param="utils.run.batch_size=('tokens_per_batch', 196608)" \
      --gin_param="utils.run.train_steps=$((PRETRAINED_STEPS + FINETUNE_STEPS))" \
      --gin_param="utils.run.init_checkpoint='${PRETRAINED_DIR}/model.ckpt-${PRETRAINED_STEPS}'" \
      --t5_tfds_data_dir="${BUCKET}/t5-tfds"
```

where the task definition is: 
```python 
import random
import t5
import os
import functools
import tensorflow as tf
from t5.data import sentencepiece_vocabulary
from t5.evaluation import metrics

DATA_DIR = "gs://danielk-files/data/"

def get_downloaded_data_path(data_dir1, split, extension):
    return os.path.join(data_dir1, split + extension)


def preprocess(
        dataset,
        prefix='',  # not used
        sample_answer=False,  # not used
):
    return dataset.filter(lambda ex: tf.strings.length(ex['targets']) > 0)


def dataset_fn_two_column(split, shuffle_files=False, dataset=""):
    # Load lines from the text file as examples.
    ds = tf.data.TextLineDataset(get_downloaded_data_path(DATA_DIR + dataset, split, ".tsv"))
    print(" >>>> about to read tsv . . . ")
    ds = ds.map(
        functools.partial(tf.io.decode_csv, record_defaults=["", ""], use_quote_delim=False, field_delim="\t"),
        num_parallel_calls=tf.data.experimental.AUTOTUNE)
    # Map each tuple to a {"question": ... "answers": ...} dict.
    ds = ds.map(lambda *ex: dict(zip(["inputs", "targets"], ex)))
    return ds

def postprocessor_two_column(answer, example=None, is_target=False):
    """Returns answer, or all answers if the full example is provided."""
    return tf.compat.as_text(answer)


for task in [
    'protocol_comparison_harsht'
]:
    t5.data.TaskRegistry.add(
        task,
        # Supply a function which returns a tf.data.Dataset.
        dataset_fn=functools.partial(dataset_fn_two_column, dataset=task),
        splits=["train", "test", "val"],
        # Supply a function which preprocesses text from the tf.data.Dataset.
        text_preprocessor=preprocess,
        # Lowercase targets before computing metrics.
        postprocess_fn=postprocessor_two_column,
        # sentencepiece_model_path=t5.data.DEFAULT_SPM_PATH,
        metric_fns=[metrics.squad]
    )
```

Here is the output log: 
```
 output_unique/UnstackOperation: 1.13e+10
 output_unique/Variable: 3.29e+07
variables: 1.13e+10
 variables/trainable: 1.13e+10
 variables/untrainable: 1.16e+07
INFO:tensorflow:Initializing variables from gs://danielk-files/t5-models/union_mixture/11B/model.ckpt-1120000:
I0119 23:18:11.574327 140220395513216 utils.py:716] Initializing variables from gs://danielk-files/t5-models/union_mixture/11B/model.ckpt-1120000:
INFO:tensorflow:Variables in gs://danielk-files/t5-models/union_mixture/11B/model.ckpt-1120000 but not in graph:
I0119 23:18:11.575031 140220395513216 utils.py:718] Variables in gs://danielk-files/t5-models/union_mixture/11B/model.ckpt-1120000 but not in graph:
INFO:tensorflow:
I0119 23:18:11.575218 140220395513216 utils.py:719]
INFO:tensorflow:Variables in graph but not in gs://danielk-files/t5-models/union_mixture/11B/model.ckpt-1120000:
I0119 23:18:11.575298 140220395513216 utils.py:720] Variables in graph but not in gs://danielk-files/t5-models/union_mixture/11B/model.ckpt-1120000:
INFO:tensorflow:
I0119 23:18:11.575422 140220395513216 utils.py:721]
INFO:tensorflow:Create CheckpointSaverHook.
I0119 23:18:16.656581 140220395513216 basic_session_run_hooks.py:546] Create CheckpointSaverHook.
INFO:tensorflow:Done calling model_fn.
I0119 23:18:17.038530 140220395513216 estimator.py:1171] Done calling model_fn.
INFO:tensorflow:TPU job name worker
I0119 23:18:33.864281 140220395513216 tpu_estimator.py:508] TPU job name worker
INFO:tensorflow:Starting the session.
I0119 23:18:33.869743 140220395513216 ops.py:5746] Starting the session.
INFO:tensorflow:Graph was finalized.
I0119 23:18:34.511712 140220395513216 monitored_session.py:246] Graph was finalized.
INFO:tensorflow:Running local_init_op.
I0119 23:19:14.174551 140220395513216 session_manager.py:505] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0119 23:19:16.983236 140220395513216 session_manager.py:508] Done running local_init_op.
WARNING:tensorflow:From /home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py:767: Variable.load (from tens
orflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer Variable.assign which has equivalent behavior in 2.X.
W0119 23:19:23.205564 140220395513216 deprecation.py:323] From /home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_est
imator.py:767: Variable.load (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer Variable.assign which has equivalent behavior in 2.X.
INFO:tensorflow:Initialized dataset iterators in 3 seconds
I0119 23:19:29.146579 140220395513216 util.py:96] Initialized dataset iterators in 3 seconds
INFO:tensorflow:Installing graceful shutdown hook.
I0119 23:19:29.147024 140220395513216 session_support.py:344] Installing graceful shutdown hook.
2021-01-19 23:19:29.147537: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:373] GrpcSession::ListDevices will initialize the session with an empty graph and other default
s because the session has not yet been created.
INFO:tensorflow:Creating heartbeat manager for ['/job:worker/replica:0/task:0/device:CPU:0', '/job:worker/replica:0/task:1/device:CPU:0', '/job:worker/replica:0/task:2/device:CPU:0'
, '/job:worker/replica:0/task:3/device:CPU:0', '/job:worker/replica:0/task:4/device:CPU:0', '/job:worker/replica:0/task:5/device:CPU:0', '/job:worker/replica:0/task:6/device:CPU:0',
 '/job:worker/replica:0/task:7/device:CPU:0', '/job:worker/replica:0/task:9/device:CPU:0', '/job:worker/replica:0/task:10/device:CPU:0', '/job:worker/replica:0/task:8/device:CPU:0',
 '/job:worker/replica:0/task:11/device:CPU:0', '/job:worker/replica:0/task:13/device:CPU:0', '/job:worker/replica:0/task:12/device:CPU:0', '/job:worker/replica:0/task:14/device:CPU:
0', '/job:worker/replica:0/task:15/device:CPU:0']
I0119 23:19:29.155493 140220395513216 session_support.py:82] Creating heartbeat manager for ['/job:worker/replica:0/task:0/device:CPU:0', '/job:worker/replica:0/task:1/device:CPU:0'
, '/job:worker/replica:0/task:2/device:CPU:0', '/job:worker/replica:0/task:3/device:CPU:0', '/job:worker/replica:0/task:4/device:CPU:0', '/job:worker/replica:0/task:5/device:CPU:0',
 '/job:worker/replica:0/task:6/device:CPU:0', '/job:worker/replica:0/task:7/device:CPU:0', '/job:worker/replica:0/task:9/device:CPU:0', '/job:worker/replica:0/task:10/device:CPU:0',
 '/job:worker/replica:0/task:8/device:CPU:0', '/job:worker/replica:0/task:11/device:CPU:0', '/job:worker/replica:0/task:13/device:CPU:0', '/job:worker/replica:0/task:12/device:CPU:0
', '/job:worker/replica:0/task:14/device:CPU:0', '/job:worker/replica:0/task:15/device:CPU:0']
INFO:tensorflow:Configuring worker heartbeat: shutdown_mode: WAIT_FOR_COORDINATOR

I0119 23:19:29.161086 140220395513216 session_support.py:105] Configuring worker heartbeat: shutdown_mode: WAIT_FOR_COORDINATOR   

INFO:tensorflow:Starting infeed thread controller.
I0119 23:19:29.175481 140215477532416 tpu_estimator.py:525] Starting infeed thread controller.
INFO:tensorflow:Starting outfeed thread controller.
I0119 23:19:29.176040 140215469139712 tpu_estimator.py:545] Starting outfeed thread controller.
INFO:tensorflow:Before copy master to slices.
I0119 23:19:29.176695 140220395513216 ops.py:5775] Before copy master to slices.
I0119 23:19:29.319628 140215460747008 transport.py:157] Attempting refresh to obtain initial access_token
I0119 23:19:30.017903 140215460747008 transport.py:157] Attempting refresh to obtain initial access_token
INFO:tensorflow:training_loop marked as finished
I0119 23:19:50.840851 140220395513216 error_handling.py:115] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0119 23:19:50.841098 140220395513216 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 264, in <module>
    console_entry_point()
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 261, in console_entry_point
    app.run(main)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 255, in main
    model_dir=FLAGS.model_dir)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 2302, in run
    skip_seen_data=skip_seen_data)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1615, in train_model
    estimator.train(input_fn=input_fn, max_steps=train_steps)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3083, in train
    rendezvous.raise_errors()
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3078, in train
    saving_listeners=saving_listeners)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1182, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1215, in _train_model_default
    saving_listeners)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1514, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 604, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1038, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 749, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1231, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1236, in _create_session
    return self._sess_creator.create_session()
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 909, in create_session
    hook.after_create_session(self.tf_sess, self.coord)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/mesh_tensorflow/ops.py", line 5776, in after_create_session
    session.run(self._op)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError:
=====================
Internal: From /job:worker/replica:0/task:3:
could not parse rpc response
         [[node stacked/decoder/block_004/layer_002/DenseReluDense/wo/kernel/Cast (defined at /site-packages/mesh_tensorflow/simd_mesh_impl.py:239) ]]
Internal: From /job:worker/replica:0/task:0:
could not parse rpc response
         [[node stacked/encoder/block_006/layer_001/DenseReluDense/wo/kernel/Cast (defined at /site-packages/mesh_tensorflow/simd_mesh_impl.py:239) ]]
=====================

Errors may have originated from an input operation.
Input Source operations connected to node stacked/decoder/block_004/layer_002/DenseReluDense/wo/kernel/Cast:
 stacked/decoder/block_004/layer_002/DenseReluDense/wo/kernel/stack (defined at /site-packages/mesh_tensorflow/ops.py:4130)

Input Source operations connected to node stacked/encoder/block_006/layer_001/DenseReluDense/wo/kernel/Cast:
 stacked/encoder/block_006/layer_001/DenseReluDense/wo/kernel/stack (defined at /site-packages/mesh_tensorflow/ops.py:4130)

Original stack trace for 'stacked/decoder/block_004/layer_002/DenseReluDense/wo/kernel/Cast':

  File "/site-packages/t5/models/mesh_transformer_main.py", line 264, in <module>
    console_entry_point()
  File "/site-packages/t5/models/mesh_transformer_main.py", line 261, in console_entry_point
    app.run(main)
  File "/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/site-packages/t5/models/mesh_transformer_main.py", line 255, in main
    model_dir=FLAGS.model_dir)
  File "/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/site-packages/mesh_tensorflow/transformer/utils.py", line 2302, in run
    skip_seen_data=skip_seen_data)
  File "/site-packages/mesh_tensorflow/transformer/utils.py", line 1615, in train_model
    estimator.train(input_fn=input_fn, max_steps=train_steps)
  File "/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3078, in train
    saving_listeners=saving_listeners)
  File "/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1182, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1211, in _train_model_default
    self.config)
  File "/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2915, in _call_model_fn
    config)
  File "/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1170, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3206, in _model_fn
    _train_on_tpu_system(ctx, model_fn_wrapper, dequeue_fn))
  File "/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3648, in _train_on_tpu_system
    device_assignment=ctx.device_assignment)
  File "/site-packages/tensorflow/python/tpu/tpu.py", line 1565, in split_compile_and_shard
    name=name)
  File "/site-packages/tensorflow/python/tpu/tpu.py", line 1280, in split_compile_and_replicate
    outputs = computation(*computation_inputs)
  File "/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3634, in multi_tpu_train_steps_on_single_shard
    inputs=[0, _INITIAL_LOSS])
  File "/site-packages/tensorflow/python/tpu/training_loop.py", line 178, in while_loop
    condition_wrapper, body_wrapper, inputs, name="", parallel_iterations=1)
  File "/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2766, in while_loop
    return_same_structure)
  File "/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2248, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2173, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/site-packages/tensorflow/python/tpu/training_loop.py", line 121, in body_wrapper
    outputs = body(*(inputs + dequeue_ops))
  File "/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3633, in <lambda>
    lambda i, loss: [i + 1, single_tpu_train_step(i)],
  File "/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1753, in train_step
    self._call_model_fn(features, labels))
  File "/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2031, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "/site-packages/mesh_tensorflow/transformer/utils.py", line 686, in my_model_fn
    log_file=model_info_file)
  File "/site-packages/mesh_tensorflow/ops.py", line 726, in __init__
    op.lower(self)
  File "/site-packages/mesh_tensorflow/ops.py", line 4040, in lower
    sv = mesh_impl.LaidOutVariable(self, mesh_impl)
  File "/site-packages/mesh_tensorflow/simd_mesh_impl.py", line 213, in __init__
    variable.get_master(), shape, slices, slice_shape)
  File "/site-packages/mesh_tensorflow/simd_mesh_impl.py", line 239, in _gen_copy_master_to_slices_op
    master_variable = tf.cast(master_variable, slices[0].dtype)
  File "/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/site-packages/tensorflow/python/ops/math_ops.py", line 789, in cast
    x = gen_math_ops.cast(x, base_type, name=name)
  File "/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1978, in cast
    "Cast", x=x, DstT=DstT, Truncate=Truncate, name=name)
  File "/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/site-packages/tensorflow/python/framework/ops.py", line 3327, in _create_op_internal
    op_def=op_def)
  File "/site-packages/tensorflow/python/framework/ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()
```

My first guess was, this could be a memory issue. 
So I tried changing the `tokens_per_batch` from `196608 ` to `98304`. 
However, it seems that `mesh` is not happy about that: 
```
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 2002, in serialize_num_microbatches
    layout_rules, mesh_shape, batch_dim)
  File "/home/danielk/anaconda3/envs/qoogle_py37/lib/python3.7/site-packages/mesh_tensorflow/ops.py", line 6478, in tensor_dim_to_size_per_split
    % (mesh_dim_size, tensor_dim))
ValueError: Mesh dimension (128) must divide tensor dimension (Dimension(name='batch', size=192))
```

For completeness, here is my environment: 
```
t5                       0.7.1
tensorboard              2.2.2
tensorboard-plugin-wit   1.7.0
tensorflow               2.2.1
tensorflow-datasets      4.1.0
tensorflow-estimator     2.2.0
tensorflow-metadata      0.25.0
tensorflow-text          2.2.1
termcolor                1.1.0
tfds-nightly             4.1.0.dev202011100107
threadpoolctl            2.1.0
tokenizers               0.9.3
torch                    1.7.0
```

CC @HarshTrivedi

**Comment by craffel** [comment]
Hi Daniel, the first error usually indicates an error on the TPU worker, which IIRC could be an OOM. Unfortunately, it's hard to debug this unless you using the "Cloud TPU VM" approach we emailed you about a while back. The second error is because your batch has size (192, sequence_length) and you are trying to use data parallelism of 128, but you can't divide 192 by 128. It looks like you are using a v3-128 TPU, so it seems you are not using any model parallelism. You can decrease the data parallelism by using more model parallelism (e.g. `--gin_param="utils.tpu_mesh_shape.model_parallelism = 2"`) or by using a smaller TPU slice.

**Comment by danyaljj** [comment]
Thanks for the prompt response! 

In case anyone else comes across the same issue, setting `model_parallelism` to `32` (T5-11B on v3-128 TPU) solved the problem: 
```
--gin_param="utils.tpu_mesh_shape.model_parallelism = 32" \
```
