### ISSUE TITLE
error failed to allocate resources and GRPC call error while m-t5 pretraining

### ISSUE THREAD

**Issue by vivektys** [google-research/text-to-text-transfer-transformer#662]
```
python -m t5.models.mesh_transformer_main    \
  --gin_file="dataset.gin"   \
  --gin_file="models/t5.1.0.large.gin" \
  --model_dir="gs://permanent-us-east1-q5loch/vivek_kaul/t5/pretraining/models/en/search_log_multi_query_base/large/"   \
  --module_import="i18n_search_log"   \
  --gin_param="MIXTURE_NAME = 'i18n_search_mlm'"   \
  --gin_param="utils.run.train_steps =  1000000"   \
  --gin_param="utils.run.save_checkpoints_steps = 4096"   \
  --gin_param="utils.run.keep_checkpoint_max = 10"   \
  --gin_param="utils.run.batch_size = (\"tokens_per_batch\", 131072)"    \
  --gin_file="learning_rate_schedules/rsqrt_no_ramp_down.gin"   \
  --gin_file="objectives/iid_15_u_u.gin"   \
  --tpu=$TPU_ADDRESS   \
  --gin_param="utils.run.sequence_length = {'inputs': 64, 'targets': 64}" \
  --gin_param="utils.tpu_mesh_shape.tpu_topology = '${TPU_TOPOLOGY}'"  \
  --gin_param="utils.tpu_mesh_shape.model_parallelism = 4"
```

I was getting an errors after 84k steps which 

```
INFO:tensorflow:Graph was finalized.
I0112 17:28:39.724309 130139942577984 monitored_session.py:246] Graph was finalized.
INFO:tensorflow:Restoring parameters from gs://permanent-us-east1-q5loch/vivek_kaul/t5/pretraining/models/en/search_log_multi_query_base/large/model.ckpt-84000
I0112 17:28:39.945981 130139942577984 saver.py:1293] Restoring parameters from gs://permanent-us-east1-q5loch/vivek_kaul/t5/pretraining/models/en/search_log_multi_query_base/large/model.ckpt-84000
I0112 17:28:51.057593 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:28:51.351440 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:29:21.619801 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:29:21.922755 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
2021-01-12 17:29:24.787253: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:160] RPC failed with status = "Unavailable: Socket closed" and grpc_error_string = "{"created":"@1610472564.787010995","description":"Error received from peer ipv4:10.199.0.86:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
I0112 17:29:52.095371 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:36:28.738291 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:36:59.044272 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:36:59.337109 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:37:29.463131 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:37:29.573544 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:37:59.852958 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:38:00.138146 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
2021-01-12 17:38:06.574765: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:160] RPC failed with status = "Unavailable: Socket closed" and grpc_error_string = "{"created":"@1610473086.574489830","description":"Error received from peer ipv4:10.199.0.86:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
I0112 17:38:30.466475 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:38:30.773213 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:39:01.040427 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:40:02.101880 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:40:02.223121 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:40:32.554190 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:40:32.868462 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
INFO:tensorflow:Running local_init_op.
I0112 17:40:52.840925 130139942577984 session_manager.py:505] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0112 17:40:54.394438 130139942577984 session_manager.py:508] Done running local_init_op.
I0112 17:41:01.630885 130139942577984 session_support.py:344] Installing graceful shutdown hook.
2021-01-12 17:41:01.631563: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:373] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.
INFO:tensorflow:Creating heartbeat manager for ['/job:worker/replica:0/task:0/device:CPU:0', '/job:worker/replica:0/task:1/device:CPU:0', '/job:worker/replica:0/task:2/device:CPU:0', '/job:worker/replica:0/task:5/device:CPU:0', '/job:work
er/replica:0/task:3/device:CPU:0', '/job:worker/replica:0/task:6/device:CPU:0', '/job:worker/replica:0/task:4/device:CPU:0', '/job:worker/replica:0/task:7/device:CPU:0']
I0112 17:41:01.638519 130139942577984 session_support.py:82] Creating heartbeat manager for ['/job:worker/replica:0/task:0/device:CPU:0', '/job:worker/replica:0/task:1/device:CPU:0', '/job:worker/replica:0/task:2/device:CPU:0', '/job:work
er/replica:0/task:5/device:CPU:0', '/job:worker/replica:0/task:3/device:CPU:0', '/job:worker/replica:0/task:6/device:CPU:0', '/job:worker/replica:0/task:4/device:CPU:0', '/job:worker/replica:0/task:7/device:CPU:0']
INFO:tensorflow:Configuring worker heartbeat: shutdown_mode: WAIT_FOR_COORDINATOR   
I0112 17:41:01.645526 130139942577984 session_support.py:105] Configuring worker heartbeat: shutdown_mode: WAIT_FOR_COORDINATOR
INFO:tensorflow:Starting infeed thread controller.
I0112 17:41:01.656913 130136053901056 tpu_estimator.py:525] Starting infeed thread controller.
INFO:tensorflow:Starting outfeed thread controller.
I0112 17:41:01.657705 130136013518592 tpu_estimator.py:545] Starting outfeed thread controller.
INFO:tensorflow:Before copy master to slices.
I0112 17:41:01.659013 130139942577984 ops.py:5767] Before copy master to slices.
I0112 17:41:01.914083 130136005125888 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:41:02.207997 130136005125888 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:41:03.179255 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
I0112 17:41:03.466193 130136037115648 transport.py:157] Attempting refresh to obtain initial access_token
INFO:tensorflow:training_loop marked as finished
I0112 17:41:04.209789 130139942577984 error_handling.py:115] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0112 17:41:04.210130 130139942577984 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/t5/models/mesh_transformer_main.py", line 262, in <module>
    console_entry_point()
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/t5/models/mesh_transformer_main.py", line 259, in console_entry_point
    app.run(main)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/t5/models/mesh_transformer_main.py", line 253, in main
    model_dir=FLAGS.model_dir)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/mesh_tensorflow/transformer/utils.py", line 2115, in run
    train_dataset_fn, train_steps, ensemble_inputs)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/mesh_tensorflow/transformer/utils.py", line 1498, in train_model
    estimator.train(input_fn=input_fn, max_steps=train_steps)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3089, in train
    rendezvous.raise_errors()
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError:
=====================
Resource exhausted: From /job:worker/replica:0/task:4:
8 root error(s) found.
  (0) Resource exhausted: Failed to allocate request for 248.0KiB (253952B) on device ordinal 6
         [[node shared/embedding_slot_vc_1/Slice_2 (defined at home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/mesh_tensorflow/simd_mesh_impl.py:250) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
Additional GRPC error information from remote target /job:worker/replica:0/task:6:  
:{"created":"@1610473264.152920883","description":"Error received from peer ipv4:10.199.0.82:8470","file":"third_party/grpc/src/core/lib/surface/call.cc","file_line":1057,"grpc_message":"Failed to allocate request for 248.0KiB (253952B) o
n device ordinal 6\n\t [[node shared/embedding_slot_vc_1/Slice_2 (defined at home/vivek_kaul_apple_com/t5-code/lib/python3.6/site-packages/mesh_tensorflow/simd_mesh_impl.py:250) ]]\nHint: If you want to see a list of allocated tensors whe
n OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\n","grpc_status":8}
         [[shared/embedding_slot_vc_1/Slice_2_S7727]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
         [[stacked/encoder/block_000/layer_000/SelfAttention/relative_attention_bias_slot_v/Slice_3_S7837_G12]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```
Any idea why this is a problem and what are the embedding slots? "shared/embedding_slot_vc_1/Slice_2"

**Comment by craffel** [comment]
That is an OOM error. You need to use a large slice, decrease your batch size, or modify your data/model parallelism.

**Comment by vkaul11** [comment]
What does larger slice mean? Larger TPU slice or is it something else ?

**Comment by craffel** [comment]
Yes, a larger TPU slice.

**Comment by vkaul11** [comment]
Sorry for the question what is the embedding slot ? Is it just what goes
into each slice ?

**Comment by craffel** [comment]
That's a variable name, referring to optimizer accumulator variables. Your error is a generic out-of-memory error, it's just coincidence that it occured in a variable that has the word "slot" in it.

**Comment by vivektys** [comment]
Each time we restart will it start from the latest checkpoint?

**Comment by vkaul11** [comment]
Can we start from from the last checkpoint before the out of memory error?
