### ISSUE TITLE
Error running pre-training on GPUs

### ISSUE THREAD

**Issue by dpanshu** [google-research/text-to-text-transfer-transformer#666]
I am getting the following the error while running the following command 
```
t5_mesh_transformer  \
  --model_dir="${MODEL_DIR}" \
  --t5_tfds_data_dir="${DATA_DIR}" \
  --gin_file="dataset.gin" \
  --gin_param="utils.run.mesh_shape = 'model:1,batch:8'" \
  --gin_param="utils.run.mesh_devices = ['gpu:0', 'gpu:1', 'gpu:2', 'gpu:3', 'gpu:4', 'gpu:5', 'gpu:6', 'gpu:7']" \
  --gin_param="MIXTURE_NAME = 'wikipedia_20190301.en_v003_unsupervised'" \
  --gin_file="models/bi_v1.gin" \
  --gin_param="utils.run.train_steps = 524288" \
  --gin_param="utils.run.save_checkpoints_steps = 5000" \
  --gin_param="utils.run.batch_size = (\"tokens_per_batch\", 65536)"  \
  --gin_file="learning_rate_schedules/rsqrt_no_ramp_down.gin" \
  --gin_file="objectives/denoise.gin"
```

```
I0122 23:33:39.875072 139876297045824 resource_reader.py:50] system_path_file_exists:dataset.gin
E0122 23:33:39.875813 139876297045824 resource_reader.py:55] Path not found: dataset.gin
I0122 23:33:39.876900 139876297045824 resource_reader.py:50] system_path_file_exists:models/bi_v1.gin
E0122 23:33:39.877060 139876297045824 resource_reader.py:55] Path not found: models/bi_v1.gin
I0122 23:33:39.877314 139876297045824 resource_reader.py:50] system_path_file_exists:models/bi_bert_base.gin
E0122 23:33:39.877456 139876297045824 resource_reader.py:55] Path not found: models/bi_bert_base.gin
I0122 23:33:39.878335 139876297045824 resource_reader.py:50] system_path_file_exists:learning_rate_schedules/rsqrt_no_ramp_down.gin
E0122 23:33:39.878494 139876297045824 resource_reader.py:55] Path not found: learning_rate_schedules/rsqrt_no_ramp_down.gin
I0122 23:33:39.879043 139876297045824 resource_reader.py:50] system_path_file_exists:objectives/denoise.gin
E0122 23:33:39.879200 139876297045824 resource_reader.py:55] Path not found: objectives/denoise.gin


Traceback (most recent call last):
  File "/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (protobuf 3.10.0 (/miniconda/lib/python3.7/site-packages), Requirement.parse('protobuf>=3.12.2'), {'tfds-nightly'})
```

**Comment by craffel** [comment]
You have a version mismatch in your Python environment - this isn't an issue with t5.
