### ISSUE TITLE
Error exporting the model

### ISSUE THREAD

**Issue by dpanshu** [google-research/text-to-text-transfer-transformer#675]
I am getting the following error exporting the model, I created a custom version of T5 model similar to https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/gin/models/t5.1.n4w10.base.gin but with fewer decoder layers
```
Traceback (most recent call last):
  File "src/train_and_evaluate_1.py", line 598, in <module>
    main()
  File "src/train_and_evaluate_1.py", line 587, in main
    export(model=model)
  File "src/train_and_evaluate_1.py", line 571, in export
    temperature=1.0,  # sample according to predicted distribution
  File "/miniconda/lib/python3.7/site-packages/t5/models/mtf_model.py", line 469, in export
    gin.parse_config_file(_operative_config_path(self._model_dir))
  File "/miniconda/lib/python3.7/site-packages/gin/config.py", line 1764, in parse_config_file
    includes, imports = parse_config(f, skip_unknown=skip_unknown)
  File "/miniconda/lib/python3.7/site-packages/gin/config.py", line 1657, in parse_config
    bind_parameter((scope, selector, arg_name), value)
  File "/miniconda/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/miniconda/lib/python3.7/site-packages/gin/utils.py", line 58, in try_with_location
    augment_exception_message_and_reraise(exception, _format_location(location))
  File "/miniconda/lib/python3.7/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/miniconda/lib/python3.7/site-packages/gin/utils.py", line 56, in try_with_location
    yield
  File "/miniconda/lib/python3.7/site-packages/gin/config.py", line 1657, in parse_config
    bind_parameter((scope, selector, arg_name), value)
  File "/miniconda/lib/python3.7/site-packages/gin/config.py", line 645, in bind_parameter
    pbk = ParsedBindingKey(binding_key)
  File "/miniconda/lib/python3.7/site-packages/gin/config.py", line 510, in __new__
    raise ValueError("No configurable matching '{}'.".format(selector))
ValueError: No configurable matching 'adafactor_decay_rate_pow'.
  In file "models/small/operative_config.gin", line 19
    adafactor_decay_rate_pow.offset = 0

```

**Comment by danyaljj** [comment]
I resolved the issue by installing the latest version of t5: https://pypi.org/project/t5/0.9.3/

**Comment by danyaljj** [comment]
I resolved the issue by installing the latest version of t5: https://pypi.org/project/t5/0.9.3/
