### ISSUE TITLE
Error when fine-tuning on TPU pod

### ISSUE THREAD

**Issue by marton-avrios** [google-research/text-to-text-transfer-transformer#680]
I get the following error when running fine-tuning on a TPU pod instead of a TPU.

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/tpu/preempted_hook.py", line 87, in run
    recoverable = self._cluster._cloud_tpu_client.recoverable()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/dist-packages/cloud_tpu_client/client.py", line 264, in recoverable
    elif FLAGS.runtime_oom_exit and self._oom_event():
  File "/usr/local/lib/python3.7/dist-packages/absl/flags/_flagvalues.py", line 491, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --runtime_oom_exit before flags were parsed.
```

**Comment by craffel** [comment]
What command are you running?

**Comment by marton-avrios** [comment]
I've found it. It's a custom script and the fix was to use `tf.app.run()` because it does some parsing that was needed. If it's not a pod then it is not necessary.
