### ISSUE TITLE
adding examples for preprocessor

### ISSUE THREAD

**Issue by dorost1234** [google-research/text-to-text-transfer-transformer#698]
Hi
Do you mind adding examples for preprocessors to help better understanding of transformation done, majority have nicely already examples, but some functions like span_corruption does not have comments explaining required input formats and adding a test which is currently a TODO in the t5 codes could be very helpful. thank you.

**Comment by dorost1234** [comment]
I am calling span_corruption using this example just to test this function, which results in error:

```
    output_features = {
    "inputs": seqio.Feature(
        vocabulary=t5.data.get_default_vocabulary(), add_eos=True,
        required=False),
    "targets": seqio.Feature(
        vocabulary=t5.data.get_default_vocabulary(), add_eos=True)
    }
    og_dataset = tf.data.Dataset.from_tensors({
        'text': 'That is good.', 'other': 'That is bad.'})
    ds = prep.rekey(og_dataset, {'inputs': None, 'targets': 'text'})
    print(ds)
    span_corruption(ds, sequence_length={'inputs':5, 'targets':5}, output_features=output_features)
```

error I got: 

`  ValueError: Index out of range using input dim 0; input has only 0 dims for '{{node strided_slice}} = StridedSlice[Index=DT_INT32, T=DT_STRING, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=0](args_1, strided_slice/stack, strided_slice/stack_1, strided_slice/stack_2)' with input shapes: [], [1], [1], [1] and with computed input tensors: input[3] = <1>.
`
adding test function for this function is a TODO in T5 codebase, do you mind adding a simple test function to help us better understand the codes ? thanks

**Comment by dorost1234** [comment]
I tried to test this function as below:

```
import collections
import functools
import t5
import tensorflow as tf
from t5.data import preprocessors as prep
from t5.data.preprocessors import  span_corruption

  output_features = {
    "inputs": seqio.Feature(
        vocabulary=t5.data.get_default_vocabulary(), add_eos=True,
        required=False),
    "targets": seqio.Feature(
        vocabulary=t5.data.get_default_vocabulary(), add_eos=True)
    }
    og_dataset = tf.data.Dataset.from_tensors({
        'text': ['That is good.', 'yes this is very gooddddd .', 'nop waydsdeddedd ey no no no'], 'other': ['That is bad.', 'no this is not very bad. :))) I love it', 'I like this product because this is fast']})
    ds = prep.rekey(og_dataset, {'inputs': None, 'targets': 'text'})
    span_corruption(ds, sequence_length={'inputs': 50, 'targets':50}, output_features=output_features)
```

This results in lots of error in denoise function, apparently the format might not be right, I appreciate assisting me with correcting this example, to understand this function. thanks

**Comment by adarob** [comment]
I think you want to use `from_tensor_slices` instead of `from_tensors`. Right now you're passing it in a single example with a 1D tensor of strings instead of the scalar it expects.

**Comment by dorost1234** [comment]
Hi
thanks but this does not still work, here is minimal example, I was wondering if you could help me make this minimal example work, this function input format is not documented in the codes, and I really need to understand this function. thank you very much

```
import functools
import t5
import tensorflow as tf
from t5 import seqio
from t5.data import preprocessors as prep
from t5.data.preprocessors import span_corruption


if __name__ == "__main__":
    output_features = {
    "inputs": seqio.Feature(
        vocabulary=t5.data.get_default_vocabulary(), add_eos=True,
        required=False),
    "targets": seqio.Feature(
        vocabulary=t5.data.get_default_vocabulary(), add_eos=True)
    }
    og_dataset = tf.data.Dataset.from_tensor_slices({
        'text': ['That is good.', 'yes this is very gooddddd .', 'nop waydsdeddedd ey no no no'], 'other': ['That is bad.', 'no this is not very bad. :))) I love it', 'I like this product because this is fast']})
    ds = prep.rekey(og_dataset, {'inputs': None, 'targets': 'text'})
    span_corruption(ds, sequence_length={'inputs': 50, 'targets':50}, output_features=output_features)
```
here are the errors:

```
Traceback (most recent call last):
  File "test_minimal.py", line 20, in <module>
    span_corruption(ds, sequence_length={'inputs': 50, 'targets':50}, output_features=output_features)
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/t5/data/preprocessors.py", line 1905, in span_corruption
    feature_key='targets', max_length=65536)
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/t5/data/preprocessors.py", line 2061, in select_random_chunk
    return _my_fn(dataset)
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/t5/seqio/utils.py", line 625, in wrapped_fn
    map_fn, num_parallel_calls=tf.data.experimental.AUTOTUNE)
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1812, in map
    preserve_cardinality=True)
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4246, in __init__
    use_legacy_function=use_legacy_function)
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3525, in __init__
    self._function = wrapper_fn.get_concrete_function()
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3052, in get_concrete_function
    *args, **kwargs)
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3019, in _get_concrete_function_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3518, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3453, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 670, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/t5/seqio/utils.py:621 None  *
        lambda x, s: fn(x, seed=s[0], *args, **kwargs)
    /user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/t5/data/preprocessors.py:2043 _my_fn  *
        chunk = {feature_key: tokens[start:end]}
    /user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py:1047 _slice_helper
        name=name)
    /user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py:1219 strided_slice
        shrink_axis_mask=shrink_axis_mask)
    /user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py:10479 strided_slice
        shrink_axis_mask=shrink_axis_mask, name=name)
    /user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:750 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py:592 _create_op_internal
        compute_device)
    /user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:3536 _create_op_internal
        op_def=op_def)
    /user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:2016 __init__
        control_input_ops, op_def)
    /user/dorost/libs/anaconda3/envs/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1856 _create_c_op
        raise ValueError(str(e))

    ValueError: Index out of range using input dim 0; input has only 0 dims for '{{node strided_slice}} = StridedSlice[Index=DT_INT32, T=DT_STRING, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=0](args_1, strided_slice/stack, strided_slice/stack_1, strided_slice/stack_2)' with input shapes: [], [1], [1], [1] and with computed input tensors: input[3] = <1>.

  In call to configurable 'select_random_chunk' (<function select_random_chunk at 0x7f6c2d050598>)
```
