### ISSUE TITLE
Run-time shape mismatch for TPUExecute argument

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#76]
I am am getting the following error while trying to run evaluation: 

```
        5254,     1]), 'targets_plaintext': b"bainbridge's", 'targets': array([7835, 9818,   31,    7,    1])}
{'inputs_plaintext': b"question: (nikola_tesla) tesla went on to pursue his ideas of wireless lighting and electricity distribution in his high-voltage, high-frequency power experiments in new york and colorado springs, and made early (1893) pronouncements on the possibility of wireless communication with his devices. he tried to put these ideas to practical use in an ill-fated attempt at intercontinental wireless transmission, his unfinished wardenclyffe tower project. in his lab he also conducted a range of experiments with mechanical oscillators/generators, electrical discharge tubes, and early x-ray imaging. he also built a wireless controlled boat, one of the first ever exhibited. what were some of tesla's experiments?", 'inputs': array([  822,    10,    41,  4953,    32,   521,   834,  1422,   521,
          61,     3,  1422,   521,   877,    30,    12,  6665,   112,
         912,    13,  5419,  3598,    11,  6373,  3438,    16,   112,
         306,    18, 10897,   545,     6,   306,    18, 30989,   579,
       12341,    16,   126, 25453,    11,   945,     9,    26,    32,
        2141,     7,     6,    11,   263,   778,  9323,  4271,    61,
       29786,  4128,    30,     8,  5113,    13,  5419,  1901,    28,
         112,  1904,     5,     3,    88,  1971,    12,   474,   175,
         912,    12,  3236,   169,    16,    46,     3,  1092,    18,
          89,   920,  3332,    44,  1413, 27339,   138,  5419,  5790,
           6,   112,    73, 19420,   615,   537,    75,   120,  7398,
        7293,   516,     5,    16,   112,  7690,     3,    88,    92,
        4468,     3,     9,   620,    13, 12341,    28,  8168, 22117,
          40,  6230,    87,   729,    49,  6230,     6,  4850, 12445,
       17927,     1]), 'targets_plaintext': b'mechanical oscillators/generators, electrical discharge tubes, and early x-ray imaging', 'targets': array([ 8168, 22117,    40,  6230,    87,   729,    49,  6230,     6,
        4850, 12445, 17927,     6,    11,   778,     3,   226,    18,
        2866, 12586,     1])}
{'inputs_plaintext': b'question: (steam_engine) the heat required for boiling the water and supplying the steam can be derived from various sources, most commonly from burning combustible materials with an appropriate supply of air in a closed space (called variously combustion chamber, firebox). in some cases the heat source is a nuclear reactor, geothermal energy, solar energy or waste heat from an internal combustion engine or industrial process. in the case of model or toy steam engines, the heat source can be an electric heating element. aside from firebox, what is another name for the space in which combustible material is burned in the engine?', 'inputs': array([  822,    10,    41,     7, 11650,   834, 20165,    61,     8,
        1678,   831,    21, 22151,     8,   387,    11,     3, 19327,
           8,  7222,    54,    36,     3,  9942,    45,   796,  2836,
           6,   167,  5871,    45,  9706,     3,   287,  3465,    17,
        2317,  1397,    28,    46,  2016,  1899,    13,   799,    16,
           3,     9,  3168,   628,    41,  9341,   796,   120, 27348,
       10751,     6,  1472,  2689,   137,    16,   128,  1488,     8,
        1678,  1391,    19,     3,     9,  6414, 24715,     6,   873,
        9269,  1982,   827,     6,  3693,   827,    42,  2670,  1678,
          45,    46,  3224, 27348,  1948,    42,  2913,   433,     5,
          16,     8,   495,    13,   825,    42,    12,    63,  7222,
        7277,     6,     8,  1678,  1391,    54,    36,    46,  2806,
        5866,  3282,     5,  5915,    45,  1472,  2689,     6,   125,
          19,   430,   564,    21,     8,   628,    16,    84,     3,
         287,     1]), 'targets_plaintext': b'combustion chamber', 'targets': array([27348, 10751,     1])}
 >>>>>>> creating dataset mixture . . .
 >>>>>> evaluations  . . .
 >>>> about to read csv . . .
 >>>> after reading csv . . .
 >>>> after mapping . . .
WARNING:tensorflow:From /home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2020-02-22 07:43:39.261890: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:370] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.
 >>>> about to read csv . . .
 >>>> after reading csv . . .
 >>>> after mapping . . .
WARNING:tensorflow:SimdMeshImpl ignoring devices ['', '', '', '', '', '', '', '']
WARNING:tensorflow:Using default tf glorot_uniform_initializer for variable encoder/block_000/layer_000/SelfAttention/relative_attention_bias  The initialzer will guess the input and output dimensions  based on dimension order.
WARNING:tensorflow:Using default tf glorot_uniform_initializer for variable decoder/block_000/layer_000/SelfAttention/relative_attention_bias  The initialzer will guess the input and output dimensions  based on dimension order.
WARNING:tensorflow:Using default tf glorot_uniform_initializer for variable decoder/block_000/layer_000/SelfAttention/relative_attention_bias  The initialzer will guess the input and output dimensions  based on dimension order.
WARNING:tensorflow:From /home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py:818: Variable.load (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer Variable.assign which has equivalent behavior in 2.X.
ERROR:tensorflow:Error recorded from infeed: From /job:worker/replica:0/task:0:
Run-time shape mismatch for TPUExecute argument[98] (VarHandles_8915694147696093427/_7:96). Expected element_type: F32
dimensions: 32000
dimensions: 512
layout {
  minor_to_major: 1
  minor_to_major: 0
  format: DENSE
}
is_dynamic_dimension: false
is_dynamic_dimension: false
; got element_type: F32
dimensions: 32128
dimensions: 512
layout {
  minor_to_major: 1
  minor_to_major: 0
  format: DENSE
}
is_dynamic_dimension: false
is_dynamic_dimension: false

         [[node TPUReplicateMetadata (defined at /home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'TPUReplicateMetadata':
  File "fine-tune-daniel.py", line 144, in <module>
    split="dev"
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/t5/models/mtf_model.py", line 252, in eval
    self._model_dir, dataset_fn, summary_dir, checkpoint_steps)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1264, in eval_model
    decodes = decode(estimator, input_fn, vocabulary, checkpoint_path)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 835, in decode
    for i, result in enumerate(result_iter):
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3072, in predict
    yield_single_examples=yield_single_examples):
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 622, in predict
    features, None, ModeKeys.PREDICT, self.config)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2857, in _call_model_fn
    config)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3393, in _model_fn
    ctx, model_fn_wrapper, dequeue_fn)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3648, in _predict_on_tpu_system
    device_assignment=ctx.device_assignment)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/tpu/tpu.py", line 1277, in split_compile_and_shard
    name=name)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/tpu/tpu.py", line 927, in split_compile_and_replicate
    num_replicas=num_replicas, use_tpu=use_tpu, **metadata_kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_tpu_ops.py", line 6105, in tpu_replicate_metadata
    name=name)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

ERROR:tensorflow:Closing session due to error From /job:worker/replica:0/task:0:
Run-time shape mismatch for TPUExecute argument[98] (VarHandles_8915694147696093427/_7:96). Expected element_type: F32
dimensions: 32000
dimensions: 512
layout {
  minor_to_major: 1
  minor_to_major: 0
  format: DENSE
}
is_dynamic_dimension: false
is_dynamic_dimension: false
; got element_type: F32
dimensions: 32128
dimensions: 512
layout {
  minor_to_major: 1
  minor_to_major: 0
  format: DENSE
}
is_dynamic_dimension: false
is_dynamic_dimension: false

         [[node TPUReplicateMetadata (defined at /home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'TPUReplicateMetadata':
  File "fine-tune-daniel.py", line 144, in <module>
    split="dev"
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/t5/models/mtf_model.py", line 252, in eval
    self._model_dir, dataset_fn, summary_dir, checkpoint_steps)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1264, in eval_model
    decodes = decode(estimator, input_fn, vocabulary, checkpoint_path)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 835, in decode
    for i, result in enumerate(result_iter):
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3072, in predict
    yield_single_examples=yield_single_examples):
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 622, in predict
    features, None, ModeKeys.PREDICT, self.config)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2857, in _call_model_fn
    config)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3393, in _model_fn
    ctx, model_fn_wrapper, dequeue_fn)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3648, in _predict_on_tpu_system
    device_assignment=ctx.device_assignment)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/tpu/tpu.py", line 1277, in split_compile_and_shard
    name=name)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/tpu/tpu.py", line 927, in split_compile_and_replicate
    num_replicas=num_replicas, use_tpu=use_tpu, **metadata_kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_tpu_ops.py", line 6105, in tpu_replicate_metadata
    name=name)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

ERROR:tensorflow:Error recorded from prediction_loop: Step was cancelled by an explicit call to `Session::Close()`.
WARNING:tensorflow:Reraising captured error
Traceback (most recent call last):
  File "fine-tune-daniel.py", line 144, in <module>
    split="dev"
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/t5/models/mtf_model.py", line 252, in eval
    self._model_dir, dataset_fn, summary_dir, checkpoint_steps)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1264, in eval_model
    decodes = decode(estimator, input_fn, vocabulary, checkpoint_path)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 835, in decode
    for i, result in enumerate(result_iter):
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3078, in predict
    rendezvous.raise_errors()
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 109, in catch_errors
    yield
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 536, in _run_infeed
    session.run(self._enqueue_ops)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: From /job:worker/replica:0/task:0:
Run-time shape mismatch for TPUExecute argument[98] (VarHandles_8915694147696093427/_7:96). Expected element_type: F32
dimensions: 32000
dimensions: 512
layout {
  minor_to_major: 1
  minor_to_major: 0
  format: DENSE
}
is_dynamic_dimension: false
is_dynamic_dimension: false
; got element_type: F32
dimensions: 32128
dimensions: 512
layout {
  minor_to_major: 1
  minor_to_major: 0
  format: DENSE
}
is_dynamic_dimension: false
is_dynamic_dimension: false

         [[node TPUReplicateMetadata (defined at /home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'TPUReplicateMetadata':
  File "fine-tune-daniel.py", line 144, in <module>
    split="dev"
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/t5/models/mtf_model.py", line 252, in eval
    self._model_dir, dataset_fn, summary_dir, checkpoint_steps)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1264, in eval_model
    decodes = decode(estimator, input_fn, vocabulary, checkpoint_path)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 835, in decode
    for i, result in enumerate(result_iter):
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3072, in predict
    yield_single_examples=yield_single_examples):
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 622, in predict
    features, None, ModeKeys.PREDICT, self.config)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2857, in _call_model_fn
    config)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3393, in _model_fn
    ctx, model_fn_wrapper, dequeue_fn)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3648, in _predict_on_tpu_system
    device_assignment=ctx.device_assignment)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/tpu/tpu.py", line 1277, in split_compile_and_shard
    name=name)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/tpu/tpu.py", line 927, in split_compile_and_replicate
    num_replicas=num_replicas, use_tpu=use_tpu, **metadata_kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_tpu_ops.py", line 6105, in tpu_replicate_metadata
    name=name)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/danielk/anaconda3/envs/env37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

```

the evaluation code looks like this, following the instructions in the [notebook](https://github.com/google-research/text-to-text-transfer-transformer/blob/master/notebooks/t5-trivia.ipynb). 
```python 
    model.batch_size = train_batch_size * 4
    model.eval(
        mixture_or_task_name="natural_questions",
        checkpoint_steps="all"
    )
```

**Comment by adarob** [comment]
Are you running this on CPU?

**Comment by danyaljj** [comment]
It's a TPU.

**Comment by adarob** [comment]
How are you setting the other params like tpu_topology and
model_parallelism?

**Comment by danyaljj** [comment]
Here is the script I am using: https://gist.github.com/danyaljj/ca4f672a5a0ab1e110e3d1dad58c8d00#file-t5-code-py-L233-L236 
The highlighted lines are where the error happens.

**Comment by adarob** [comment]
What size is daniels-tpu6?

**Comment by danyaljj** [comment]
The relevant TPU spec: 
<img width="229" alt="Screen Shot 2020-02-07 at 2 10 32 PM" src="https://user-images.githubusercontent.com/2441454/74058247-9d954300-49b3-11ea-81e6-2c033cd870df.png">

**Comment by craffel** [comment]
Hi Daniel, the 32,000 vs 32,128 shape mismatch mentioned makes me think you are not telling the model there are "extra IDs" in the vocab (which were used as sentinel tokens during pre-training).
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/sentencepiece_vocabulary.py#L38
This should be done when the gin param
SentencePieceVocabulary.extra_ids = 100
is bound (it will be rounded up to 128). I don't know why the model wouldn't be getting that. Can you share your modified colab?

**Comment by danyaljj** [comment]
Sorry for the delay.  Here is the complete code I am running. 
https://gist.github.com/danyaljj/288b58427c50f9ef844a767276d430f7

**Comment by danyaljj** [comment]
More thoughts on this thread: 

- I updated to the latest release (0.2.0) and the issue still remains. 
- I tried the same code on multiple other datasets (SQuAD and RACE) and getting the same error. 
- I am realizing that in [many of your experiments](https://github.com/google-research/text-to-text-transfer-transformer/search?utf8=%E2%9C%93&q=extra_ids&type=) you had the option of `sentencepiece_vocabulary.SentencePieceVocabulary.extra_ids = 100`. Wondering how I can include it in my Python code.

**Comment by danyaljj** [comment]
Just before the evaluation, I add several lines to print the vocabulary size: 

```python
    vocabulary1 = t5.data.get_mixture_or_task("natural_questions").get_vocabulary()
    print(" ******** vocabulary1")
    print(vocabulary1)
    print(vocabulary1.vocab_size)

    vocabulary2 = t5.data.SentencePieceVocabulary(t5.data.DEFAULT_SPM_PATH)
    print(" ******** vocabulary2")
    print(vocabulary2)
    print(vocabulary2.vocab_size)
```

the corresponding output output is: 
```
 ******** vocabulary1
<t5.data.sentencepiece_vocabulary.SentencePieceVocabulary object at 0x7f53ccab15d0>
32000
 ******** vocabulary2
<t5.data.sentencepiece_vocabulary.SentencePieceVocabulary object at 0x7f53cb9f4b50>
32000
```
and the output dimensions sound right. Still not sure where a vocabulary of size "32128" is coming from.

**Comment by danyaljj** [comment]
Did a bit of surgery and it seems to "work" now. I opened the content of your `model.eval` function,  and created a vocabulary with a bigger size: set `extra_ids=100`. 

```    # evaluation
    # model.eval(
    #     mixture_or_task_name="my_task",
    #     checkpoint_steps="all",
    #     # summary_dir=EVAL_SUMMARY,
    #     split="dev"
    # )

    from t5.models.mesh_transformer import mesh_eval_dataset_fn
    from mesh_tensorflow.transformer import utils

    checkpoint_steps = 'all'
    summary_dir = None

    vocabulary2 = t5.data.SentencePieceVocabulary(t5.data.DEFAULT_SPM_PATH, 100)

    dataset_fn2 = functools.partial(
        mesh_eval_dataset_fn, mixture_or_task_name="natural_questions")
    with gin.unlock_config():
      gin.parse_config_file(_operative_config_path(model._model_dir))
    utils.eval_model(model.estimator(vocabulary2), vocabulary2,
                     model._sequence_length, train_batch_size, "dev",
                     model._model_dir, dataset_fn2, summary_dir, checkpoint_steps)
```

It does produce outputs to the bucket, although the quality is not so good (for SQUAD). Wondering if: 
 - changing the vocab size messed up my predictions 
 - or I just didn't set the parameters right didn't train model for enough steps (in which case, it is an orthogonal issues to this issue.)

**Comment by craffel** [comment]
Hi Daniel, sorry to disappear for a minute, was on vacation. The `SentencePieceVocabulary.extra_ids = 100` is indeed necessary since it was used during pre-training and will result in a different embedding size. The thing I'm surprised about is that youre model didn't pick that up from the operative config. I'm not sure why that didn't happen.

Regarding why the results are bad, I'm not sure. How many steps did you train for and what was the batch size (in tokens)?

**Comment by danyaljj** [comment]
> The thing I'm surprised about is that youre model didn't pick that up from the operative config. I'm not sure why that didn't happen. 

I see. Any experiment I can run to help clarify this issue? 
Also, would it make sense to add an option to `eval()` function to be able to specify `extra_ids`? s

------- 

> Regarding why the results are bad, I'm not sure. How many steps did you train for and what was the batch size (in tokens)? 

PS. I tried for many (~2M) iterations, but then realized that my issue is the short length of my input/output encoding. There is still some performance mismatch which I will discuss in a different thread.

**Comment by craffel** [comment]
Hm, actually looking at your code snippet the issue might just be that you want to run 
```
    with gin.unlock_config():
      gin.parse_config_file(_operative_config_path(model._model_dir))
```
at the top, not after you load the vocabs and etc. That should get the `extra_ids` arg passed into the vocab kwarg.

**Comment by danyaljj** [comment]
Will try this and will get back to you 👍

**Comment by danyaljj** [comment]
@craffel  that fixes it!

**Comment by working12** [comment]
> @craffel that fixes it!

Can you share your solution here? (The snippet and changes that fixed the code).
