### ISSUE TITLE
TypeError: _get_dataset_for_single_task() got an unexpected keyword argument 'sequence_length'

### ISSUE THREAD

**Issue by puraminy** [google-research/text-to-text-transfer-transformer#790]
I got the following error in evaluation
```

model.batch_size = train_batch_size * 4
model.eval(
    mixture_or_task_name="trivia_all",
    checkpoint_steps=-1 #"all"
)
```

```

Traceback (most recent call last):
  File "train.py", line 140, in <module>
    checkpoint_steps=-1 #"all"
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/t5/models/mtf_model.py", line 267, in eval
    self._model_dir, dataset_fn, summary_dir, checkpoint_steps)
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 2025, in eval_model
    for d in decode(estimator, input_fn, vocabulary, checkpoint_path)
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 2024, in <listcomp>
    d.decode("utf-8") if isinstance(d, bytes) else d
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1114, in decode
    for i, result in enumerate(result_iter):
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3132, in predict
    rendezvous.raise_errors()
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3126, in predict
    yield_single_examples=yield_single_examples):
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 611, in predict
    input_fn, ModeKeys.PREDICT)
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1007, in _get_features_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3041, in _call_input_fn
    return input_fn(**kwargs)
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1182, in input_fn
    ds = dataset.dataset_fn(sequence_length=sequence_length)
TypeError: _get_dataset_for_single_task() got an unexpected keyword argument 'sequence_length'

```
There is a similar issue but I didn't get the solution which is one line.

https://github.com/google-research/text-to-text-transfer-transformer/issues/631

**Comment by puraminy** [comment]
I had installed `t5 v0.6.0`, which wasn't the newest version. When I installed v0.9.0, the problem was resolved. 

`pip install t5==0.9.0`
