### ISSUE TITLE
ecal can't find validation targets file!!

### ISSUE THREAD

**Issue by puraminy** [google-research/text-to-text-transfer-transformer#791]
In the evaluation part, I got the following error. Shouldn't it create the target, input, and prediction files? Then why it looks for the target_files. I  could create these files and evaluate the model with `small` model, but now in `large` model, I got this error!!!

```
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    checkpoint_steps="all"
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/t5/models/mtf_model.py", lin$
 347, in eval
    batch_size=self._batch_size)
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/t5/evaluation/eval_utils.py"$
 line 331, in run_eval
    summary_dir, cached_targets, cached_datasets)
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/t5/models/utils.py", line 89,
 in write_targets_and_examples
    write_lines_to_file(targets[task], targets_filename)
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/t5/models/utils.py", line 45,
 in write_lines_to_file
    output_file.write("\n".join([str(l) for l in lines]))
 File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file
_io.py", line 101, in write
    self._prewrite_check()
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file
_io.py", line 87, in _prewrite_check
    compat.as_bytes(self.__name), compat.as_bytes(self.__mode))
tensorflow.python.framework.errors_impl.NotFoundError: /drive3/pouramini/models/t5/large_ful
l/validation_eval/atomic_context_free_targets; No such file or directory

```

**Comment by puraminy** [comment]
The error was due to the missing of `summary_dir`. I don't know where you create `summary_dir`. 

Anyway, I hacked the t5 code by calling `makdirs` in `write_targets_and_examples` function in `t5/models/utils.py'

So, you may consider it a **bug** or suggest to me the standard way to resolve this problem.

```python
def write_targets_and_examples(summary_dir, targets, datasets):
  """Writes plaintext targets and inputs to the summary directory.

  Args:
    summary_dir: str, directory to store plaintext targets and examples
    targets: dict, task_name -> targets for each task.
    datasets: dict, task_name -> tf.data.Dataset for each task.
  """
  if targets.keys() != datasets.keys():
    raise ValueError("Targets and datasets must have the same tasks.")

  for task in targets.keys():
    targets_filename = os.path.join(
        summary_dir,
        "{}_targets".format(task),
    )
   # Pouramini: this line was added by me
    tf.io.gfile.makedirs(summary_dir)
    write_lines_to_file(targets[task], targets_filename)

```
