### ISSUE TITLE
Failed to run T5

### ISSUE THREAD

**Issue by notooth1** [google-research/text-to-text-transfer-transformer#797]
I got this error when running T5 on my local machine. Please help.

```
$ t5_mesh_transformer \
  --model_dir="/home/notooth/Google/T5/small" \
  --gin_file="/home/notooth/Google/T5/small/pretrained_models_small_operative_config.gin" \
  --gin_param="utils.run.mesh_shape='model:1,batch:1'" \
  --gin_param="utils.run.mesh_devices=['gpu:0']" \  
  --gin_param="input_filename='/home/notooth/inputs.txt'" \
  --gin_param="output_filename='/home/notooth/outputs.txt'" \
  --gin_param="infer_checkpoint_step='all'"

.....

W0418 23:30:15.178183 140090376628032 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "/home/notooth/anaconda3/bin/t5_mesh_transformer", line 8, in <module>
    sys.exit(console_entry_point())
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/t5/models/mesh_transformer_main.py", line 279, in console_entry_point
    app.run(main)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/t5/models/mesh_transformer_main.py", line 268, in main
    utils.run(
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/mesh_tensorflow/transformer/utils.py", line 2598, in run
    train_model_fn(estimator, vocabulary, sequence_length, batch_size,
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/mesh_tensorflow/transformer/utils.py", line 1815, in train_model
    estimator.train(input_fn=input_fn, max_steps=train_steps, hooks=hooks)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3130, in train
    rendezvous.raise_errors()
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3120, in train
    return super(TPUEstimator, self).train(
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1201, in _train_model_default
    self._get_features_and_labels_from_input_fn(input_fn, ModeKeys.TRAIN))
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1037, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3082, in _call_input_fn
    return input_fn(**kwargs)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/mesh_tensorflow/transformer/utils.py", line 1792, in input_fn
    dataset = train_dataset_fn(
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/t5/models/mesh_transformer.py", line 77, in mesh_train_dataset_fn
    ds = mixture_or_task.get_dataset(
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/t5/seqio/dataset_providers.py", line 1207, in get_dataset
    if split not in task.splits:
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/t5/seqio/dataset_providers.py", line 730, in splits
    return self.source.splits
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/t5/seqio/dataset_providers.py", line 343, in splits
    return self._splits or self._tfds_dataset.info.splits
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/t5/seqio/utils.py", line 102, in info
    return self.builder.info
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/t5/seqio/utils.py", line 96, in builder
    LazyTfdsLoader._MEMOIZED_BUILDERS[builder_key] = tfds.builder(
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/tensorflow_datasets/core/load.py", line 172, in builder
    return cls(**builder_kwargs)  # pytype: disable=not-instantiable
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builder.py", line 949, in __init__
    super().__init__(**kwargs)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builder.py", line 179, in __init__
    self._version = self._pick_version(version)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builder.py", line 267, in _pick_version
    raise AssertionError(msg)
AssertionError: Failed to construct dataset squad: Dataset squad cannot be loaded at version 2.0.0, only: 3.0.0.
  In call to configurable 'mesh_train_dataset_fn' (<function mesh_train_dataset_fn at 0x7f690be5a940>)
  In call to configurable 'run' (<function run at 0x7f690be5ab80>)
bash: --gin_param=input_filename='/home/notooth/inputs.txt': No such file or directory
```

**Comment by sharannarang** [comment]
The squad version issue is fixed at head. Please download the latest code and this problem will go away.
