### ISSUE TITLE
Training T5 on the new TPU-VM fails

### ISSUE THREAD

**Issue by agemagician** [google-research/text-to-text-transfer-transformer#830]
**Describe the bug**
I am trying to train t5 on the new Google TPU-VM, but it fails to find any cores on the system.
The same code runs perfectly fine on normal Google TPUs.

**To Reproduce**
1. Create a new tpu-vm:
gcloud alpha compute tpus tpu-vm create vm-tpu   --zone=us-east1-d   --accelerator-type=v3-128   --version=v2-alpha --preemptible
2. Access the tpu-vm:
gcloud alpha compute tpus tpu-vm ssh vm-tpu --zone us-east1-d  --project x
3. install t5:
pip install t5
4. Run the training command.
5. Afterwards the following error occurs:
```                                               
INFO:tensorflow:Querying Tensorflow master (grpc://10.142.15.217:8470) for TPU system metadata.                                              
I0526 20:50:05.832202 140620607282240 tpu_system_metadata.py:90] Querying Tensorflow master (grpc://10.142.15.217:8470) for TPU system metada
ta.                                                                                                                                          
2021-05-26 20:50:05.833463: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:373] GrpcSession::ListDevices will initialize the sessi
on with an empty graph and other defaults because the session has not yet been created.                                                      
INFO:tensorflow:training_loop marked as finished                                                                                             
I0526 20:50:05.837406 140620607282240 error_handling.py:115] training_loop marked as finished                                                
WARNING:tensorflow:Reraising captured error                                                                                                  
W0526 20:50:05.837576 140620607282240 error_handling.py:149] Reraising captured error                                                        
Traceback (most recent call last):                                                                                                           
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main                                                                       
    return _run_code(code, main_globals, None,                                                                                               
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code                                                                                  
    exec(code, run_globals)                                                                                                                  
  File "/home/ahmed/.local/lib/python3.8/site-packages/t5/models/mesh_transformer_main.py", line 282, in <module>                            
    console_entry_point()                                                                                                                    
  File "/home/ahmed/.local/lib/python3.8/site-packages/t5/models/mesh_transformer_main.py", line 279, in console_entry_point                 
    app.run(main)                                                                                                                            
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 303, in run                                                                
    _run_main(main, args)                                                                                                                    
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 251, in _run_main                                                          
    sys.exit(main(argv))                                                                                                                     
  File "/home/ahmed/.local/lib/python3.8/site-packages/t5/models/mesh_transformer_main.py", line 268, in main                                
    utils.run(                                                                                                                               
  File "/home/ahmed/.local/lib/python3.8/site-packages/gin/config.py", line 1069, in gin_wrapper                                             
    utils.augment_exception_message_and_reraise(e, err_str)           
  File "/home/ahmed/.local/lib/python3.8/site-packages/mesh_tensorflow/transformer/utils.py", line 2598, in run                      [0/1914]
    train_model_fn(estimator, vocabulary, sequence_length, batch_size,
  File "/home/ahmed/.local/lib/python3.8/site-packages/mesh_tensorflow/transformer/utils.py", line 1815, in train_model
    estimator.train(input_fn=input_fn, max_steps=train_steps, hooks=hooks)
  File "/home/ahmed/.local/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3110, in train
    rendezvous.raise_errors()
  File "/home/ahmed/.local/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_error
s
    six.reraise(typ, value, traceback)
  File "/home/ahmed/.local/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/ahmed/.local/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3100, in train
    return super(TPUEstimator, self).train(
  File "/home/ahmed/.local/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 346, in train
    hooks.extend(self._convert_train_steps_to_hooks(steps, max_steps))
  File "/home/ahmed/.local/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2973, in _convert_t$
ain_steps_to_hooks
    if ctx.is_running_on_cpu():
  File "/home/ahmed/.local/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 531, in is_running_on$
cpu
    self._validate_tpu_configuration()
  File "/home/ahmed/.local/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 699, in _validate_tpu$
configuration
    num_cores = self.num_cores
  File "/home/ahmed/.local/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 429, in num_cores
    metadata = self._get_tpu_system_metadata()
  File "/home/ahmed/.local/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 333, in _get_tpu_syst$
m_metadata
    tpu_system_metadata_lib._query_tpu_system_metadata(
  File "/home/ahmed/.local/lib/python3.8/site-packages/tensorflow/python/tpu/tpu_system_metadata.py", line 135, in _query_tpu_system_metadat$
    raise RuntimeError(
RuntimeError: Cannot find any TPU cores in the system (master address grpc://10.142.15.217:8470). This usually means the master address is i$
correct or the TPU worker has some problems. Available devices: []
  In call to configurable 'run' (<function run at 0x7fe27d308550>)
```

However, before the error occurred, I can see it sees the IP address for all the tpus:
```
cluster_def {                         
  job {                                                                                                                                          name: "worker"       
    tasks {                                                                                                                                  
      key: 0                                                                                                                                 
      value: "10.142.15.217:8470"                                                                                                            
    }                                                                                                                                            tasks {                                                                                                                                  
      key: 1                                                                                                                                 
      value: "10.142.15.218:8470"                                                                                                            
    }                                                                                                                                        
    tasks {                                                                                                                                        key: 2                                                                                                                                 
      value: "10.142.15.222:8470"                                                                              
    }                                                                 
    tasks {                                                                                                            
      key: 3                                                                                   
      value: "10.142.15.210:8470"                                                                                                            
    }                        
    tasks {
      key: 4
      value: "10.142.15.219:8470"
    }
    tasks {
      key: 5
      value: "10.142.15.220:8470"
    }
    tasks {
      key: 6
      value: "10.142.15.223:8470"
......
...

```

**Expected behavior**
The training should start normally because it works fine with tpu version 2.4, but not with v2-alpha

**Screenshots**
![Screenshot from 2021-05-26 23-02-37](https://user-images.githubusercontent.com/6087313/119730918-95963680-be76-11eb-922d-c6cdf4b48570.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser: None
 - Version: 20.04.2 LTS

**Additional context**
I know that tpu-vm is a beta release, but I hope it could work with t5, because it is going to save a lot of money for researchers.

**Comment by agemagician** [comment]
@craffel @adarob I will be very grateful if you could help here.

**Comment by agemagician** [comment]
I have found the solution.
The problem exists in the first step. The TPU version should be "v2-alpha-pod" for a pod rather than "v2-alpha" if a TPU pod is used.
